<?php


    // TYLKO Z TEJ TABLICY GENEROWANE SĄ SAMPLE
    // URUCHOMIENIE W KONSOLI:
    // php index.php
    $slownik = array(
            array('słowa do przeczytania','nazwa_pliku_wynikowego'),
    );



    // TABLICE Z SAMPLAMI DO MODUŁÓW
    $airly = array(
        array('pył zawieszony Pe eM 1','pyl__zawieszony_pm1'),
        array('pył zawieszony Pe eM 10','pyl__zawieszony_pm10'),
        array('pył zawieszony Pe eM 2 i pięć dziesiątych','pyl__zawieszony_pm25'),

        array('bardzo dobry','bardzo_dobry'),
        array('dobry','dobry'),
        array('umiarkowany','umiarkowany'),
        array('zly','zły'),
        array('bardzo zły','bardzo_zly'),

        array('stan_ogólny ','stan_ogolny'),

        array('airly','airly'),
        array('godzina','godzina'),
    );


    
    /// PROPAGACJA
    $slownikPropagacja = array(
        array('rigreferens','rigreference'),
        array('rigreferens kom','rigreference_com'),
        array('noaa','noaa'),

        array('dzień ','dzien'),
        array('noc','noc'),

        array('informacje o propagacji','informacje_o_propagacji'),
        array('pasma','pasma'),

        array('warunki podwyższone','warunki_podwyzszone'),
        array('warunki normalne','warunki_normalne'),
        array('warunki obniżone','warunki_obnizone'),
        array('pasmo zamknięte','pasmo_zamkniete'),

        array('160 metrów','160_metrow'),
        array('80 metrów','80_metrow'),
        array('40 metrów','40_metrow'),
        array('20 metrów','20_metrow'),
        array('10 metrów','10_metrow'),
        array('6 metrów','6_metrow'),
    );


	/// OPEN WEATHER MAP
    $slownikOpenWeathermap = array(
        array('ołpenłeder map','open_weather_map'),
        array('burza z lekkimi opadami deszczu'),
        array('burza z opadami deszczu'),
        array('burza z silnymi opadami deszczu'),
        array('niewielka burza'),
        array('burza'),
        array('silna burza'),
        array('przelotna burza'),
        array('burza z lekką mżawką','burza_z_lekka_mzawka'),
        array('burza z mżawką','burza_z_mzawka'),
        array('burza z silną mżawką','burza_z_silna_mzawka'),

        array('lekka mżawka','lekka_mzawka'),
        array('mżawka','mzawka'),
        array('silna mżawka','silna_mzawka'),
        array('lekki mżący deszcz','lekki_mzacy_deszcz'),
        array('mżący deszcz','mzacy_deszcz'),
        array('silny mżący deszcz','silny_mzacy_deszcz'),
        array('ulewa z mżawką','ulewa_z_mzawka'),
        array('silna ulewa z mżawką','silna_ulewa_z_mzawka'),
        array('ulewa z mżawką','ulewa_z_mzawka'),

        array('lekkie opady deszczu'),
        array('umiarkowane opady deszczu'),
        array('intensywne opady deszczu'),
        array('bardzo intensywne opady deszczu'),
        array('oberwanie chmury'),
        array('marznący deszcz','marznacy_deszcz'),
        array('lekka ulewa'),
        array('ulewa'),
        array('silna ulewa'),
        array('przelotna ulewa'),

        array('niewielkie opady śniegu','niewielkie_opady_sniegu'),
        array('opady śniegu','opady_sniegu'),
        array('intensywne opady sniegu','intensywne_opady_sniegu'),
        array('śnieg z deszczem','snieg_z_deszczem'),
        array('śnieg z deszczem','snieg_z_deszczem'),
        array('śnieg z niewielkim deszczem','snieg_z_niewielkim_deszczem'),
        array('śnieg z deszczem','snieg_z_deszczem'),
        array('lekka snieżyca','lekka_sniezyca'),
        array('śnieżyca','sniezyca'),
        array('intensywna śnieżyca','intensywna_sniezyca'),

        array('zamglenia'),
        array('zadymienie'),
        array('mgła','mgla'),
        array('kusz i piach','kurz_i_piach'),
        array('mgła','mgla'),
        array('piasek','piasek'),
        array('pył','pyl'),
        array('pył wulkaniczny','pyl_wulkaniczny'),
        array('szkwały','szkwaly'),
        array('tornado'),

        array('bezhmurnie','bezchmurnie'),
        array('lekkie zachmurzenie','lekkie_zachmurzenie'),
        array('niewielkie zachmurzenie','niewielkie_zachmurzenie'),
        array('zachmurzenie umiarkowane','zachmurzenie_umiarkowane'),
        array('pochmurno','pochmurno')
    );





    $slownikSDFSD = array(
         array('wiatr'),
        array('stacja pomiarowa'),
        array('tlenek węgla','tlenek_we_gla'),
        array('pył zawieszony Pe eM 10','pyl__zawieszony_pm10'),
        array('benzen','benzen'),
        array('dwutlenek azotu','dwutlenek_azotu'),
        array('pył zawieszony Pe eM 2.5','pyl__zawieszony_pm25'),
        array('dwutlenek siarki','dwutlenek_siarki'),
        array('ozon','ozon'),

		array('Wrocław - Bartnicza','wrocl_aw___bartnicza'),
		array('Wrocław - Korzeniowskiego','wrocl_aw___korzeniowskiego'),
		array('Wrocław - Wiśniowa','wrocl_aw___wis_niowa'),
		array('Legnica - Rzeczypospolitej','legnica___rzeczypospolitej'),
		array('Wałbrzych - Wysockiego','wal_brzych___wysockiego'),
		array('Czerniawa','czerniawa'),
		array('Działoszyn','dzial_oszyn'),
		array('Dzierżoniów - Piłsudskiego','dzierz_onio_w___pil_sudskiego'),
		array('Kłodzko - Szkolna','kl_odzko___szkolna'),
		array('Nowa Ruda - Srebrna','nowa_ruda___srebrna'),
		array('Oława - Żołnierzy AKa','ol_awa___z_ol_nierzy_ak'),
		array('Osieczów','osieczo_w'),
		array('Śnieżka','s_niez_ka'),
		array('Ząbkowice Śląskie','za_bkowice_s_la_skie'),
		array('Zgorzelec - Bohaterów Getta','zgorzelec___bohatero_w_getta'),
		array('Jelenia Góra - Ogińskiego','jelenia_go_ra___ogin_skiego'),
		array('Lądek-Zdrój','la_dek_zdro_j'),
		array('Lubań','luban_'),
		array('Bydgoszcz Plac Poznański','bydgoszcz_plac_poznan_ski'),
		array('Bydgoszcz Warszawska','bydgoszcz_warszawska'),
		array('Łódź-Widzew','l_o_dx__widzew'),
		array('Łódź-Gdańska 16','l_o_dx__gdan_ska_16'),
		array('Pabianice-Polfa','pabianice_polfa'),
		array('Zgierz-Śródmieście','zgierz_s_ro_dmies_cie'),
		array('Łódź-Jana Pawła drugiego piętnaście','l_o_dx__jana_pawl_a_ii_15'),
		array('Gajew','gajew'),
		array('Parzniewice','parzniewice'),
		array('Piotrków Tryb.-Krakowskie Przedmieście','piotrko_w_tryb_krakowskie_przedmies_cie'),
		array('Radomsko-Rolna 2','radomsko_rolna2'),
		array('Żyrardów-Roosevelta','z_yrardo_w_roosevelta'),
		array('Guty Duże','guty_duz_e'),
		array('Konstancin-Jeziorna-Wierzejewskiego','konstancin_jeziorna_wierzejewskiego'),
		array('Opole manualna 4','opole_manualna_4'),
		array('Opole automat 5','opole_automat_5'),
		array('Kędzierzyn-Koźle automat 1','k_kox_le_automat_1'),
		array('Olesno automat 4','olesno_automat_4'),
		array('Zdzieszowice automat 2','zdzieszowice_automat_2'),
		array('Rzeszów-Nowe Miasto','rzeszo_w_nowe_miasto'),
		array('Jaslo-Sikorskiego','jaslo_sikorskiego_wios'),
		array('Nisko-Szklarniowa-','nisko_szklarniowa_wios'),
		array('Przemysl-Grunwaldzka-WIOS','przemysl_grunwaldzka_wios'),
		array('WIOŚ Gołdap ulica Jaćwieska','wios__gol_dap_ul_jac_wieska'),
		array('KMŚ Puszcza Borecka','kms__puszcza_borecka'),
		array('WIOŚ Ełk','wios__el_k'),
		array('WIOŚ Ostróda Piłsudskiego','wios__ostro_da_pil_sudskiego'),
		array('Poznan-Polanka','poznan_polanka'),
		array('Poznan-Dabrowskiego','poznan_dabrowskiego'),
		array('Kalisz-Wyszynskiego','kalisz_wyszynskiego'),
		array('Konin-Wyszynskiego','konin_wyszynskiego'),
		array('Pila, ulica Kusocinkiego','pila_ul_kusocinkiego'),
		array('Piaski-Krzyzowka','piaski_krzyzowka'),
		array('Borowiec-Drapalka','borowiec_drapalka'),
		array('Kozieglowy-osiedle Lesne','kozieglowy_oslesne'),
		array('Szczecin_Andrzejewskiego','szczecin_andrzejewskiego'),
		array('Szczecin_Piłsudskiego','szczecin_pil_sudskiego'),
		array('Szczecin_Łączna','szczecin_l_a_czna'),
		array('Koszalin_ArmiiKrajowej','koszalin_armiikrajowej'),
		array('Widuchowa','widuchowa'),
		array('Szczecinek_Przemysłowa','szczecinek_przemysl_owa'),
		array('Dąbrowa Górnicza, Tysiąclecia 25','da_browa_go_rnicza_ul_tysia_clecia_25a'),
		array('Gliwice, ulica Mewy 34','gliwice_ul_mewy_34'),
		array('Katowice, ulica Plebiscytowa/A4','katowice_ul_plebiscytowa/a4'),
		array('Katowice, ulica Kossutha 6','katowice_ul_kossutha_6'),
		array('Sosnowiec, ulica Lubelska 51','sosnowiec_ul_lubelska_51'),
		array('Tychy, ulica Tołstoja 1','tychy_ul_tol_stoja_1'),
		array('Rybnik, ulica Borki 37 d','rybnik_ul_borki_37_d'),
		array('Żory, Sikorskiego 52','z_ory_os_gen_wl_adysl_awa_sikorskiego_52_2'),
		array('Bielsko-Biała, ulica Kossak-Szczuckiej 19','bielsko_bial_a_ul_kossak_szczuckiej_19'),
		array('Częstochowa, ulica Jana Pawła drugiego','cze_stochowa_ul_ak/jana_pawl_a_ii'),
		array('Częstochowa, ulica Baczyńskiego 2','cze_stochowa_ul_baczyn_skiego_2'),
		array('Cieszyn, ulica Mickiewicza 13','cieszyn_ul_mickiewicza_13'),
		array('Ustroń, ulica Sanatoryjna 7','ustron__ul_sanatoryjna_7'),
		array('Wodzisław Śląski, ulica Gałczyńskiego 1','wodzisl_aw_s_la_ski_ul_gal_czyn_skiego_1'),
		array('Złoty Potok, Leśniczówka','zl_oty_potok_les_niczo_wka'),
		array('Żywiec, ulica Kopernika  83','z_ywiec_ul_kopernika__83_a'),
		array('Czerwionka-Leszczyny, ulica Kopalniana','czerwionka_leszczyny_ul_kopalniana'),
		array('Kielce, ulica Jagiellońska','kielce_ul_jagiellon_ska'),
		array('Nowiny, ulica Parkowa','nowiny_ul_parkowa'),
		array('Połaniec, ulica Ruszczańska','pol_aniec_ul_ruszczan_ska'),
		array('Starachowice, ulica Złota','starachowice_ul_zl_ota'),
		array('Końskie, MOBILNA','kon_skie_mobilna'),
		array('Małogoszcz, ulica Słoneczna','mal_ogoszcz_ul_sl_oneczna'),
		array('WIOŚ Olsztyn ulica Puszkina','wios__olsztyn_ul_puszkina'),
		array('WIOŚ Elbląg ulica Bażyńskiego','wios__elbla_g_ul_baz_yn_skiego'),
		array('Kraków, Aleja Krasińskiego','krako_w_aleja_krasin_skiego'),
		array('Kraków, ulica Bujaka','krako_w_ul_bujaka'),
		array('Kraków, ulica Bulwarowa','krako_w_ul_bulwarowa'),
		array('Kraków, ulica Dietla','krako_w_ul_dietla'),
		array('Kraków, ulica Złoty Róg','krako_w_ul_zl_oty_ro_g'),
		array('Kraków, osiedle Piastów','krako_w_os_piasto_w'),
		array('Kraków, ulica Telimeny','krako_w_ul_telimeny'),
		array('Kraków, osiedle Wadów','krako_w_os_wado_w'),
		array('Tarnów, ulica Bitwy pod Studziankami','tarno_w_ul_bitwy_pod_studziankami'),
		array('Tarnów, ulica Ks. Romana Sitko','tarno_w_ul_ks_romana_sitko'),
		array('Nowy Sącz, ulica Nadbrzeżna','nowy_sa_cz_ul_nadbrzez_na'),
		array('Krempna-MPN-WIOS','krempna_mpn_wios'),
		array('Rymanów-Zdrój-Samorząd','rymano_w_zdro_j_samorza_d'),
		array('Mielec-Biernackiego-WIOS','mielec_biernackiego_wios'),
		array('Białystok-Miejska','bial_ystok_miejska'),
		array('Białystok-Warszawska','bial_ystok_warszawska'),
		array('Borsukowizna-Wiejska','borsukowizna_wiejska'),
		array('Lomza Sikorskiego 48/94','lomza_sikorskiego_48/94'),
		array('Augustów - mobilne ','augusto_w___mobilne_'),
		array('Gdańsk Śródmieście','am1_gdan_sk_s_ro_dmies_cie'),
		array('Gdańsk Stogi','am2_gdan_sk_stogi'),
		array('Gdańsk Nowy Port','am3_gdan_sk_nowy_port'),
		array('Gdynia Pogórze','am4_gdynia_pogo_rze'),
		array('Gdańsk Szadółki','am5_gdan_sk_szado_l_ki'),
		array('Sopot','am6_sopot'),
		array('Gdańsk Wrzeszcz','am8_gdan_sk_wrzeszcz'),
		array('Gdynia Dąbrowa','am9_gdynia_da_browa'),
		array('Gdynia Śródmieście','am10_gdynia_s_ro_dmies_cie'),
		array('Słupsk Kniaziewicza','am11_sl_upsk_kniaziewicza'),
		array('Kościerzyna Targowa','am12_kos_cierzyna_targowa'),
		array('Malbork Mickiewicza','am15_malbork_mickiewicza'),
		array('Lębork Malczewskiego','am16_le_bork_malczewskiego'),
		array('Liniewko Kościerskie','am17_liniewko_kos_cierskie'),
		array('IMGW Łeba - Rąbka','imgw_l_eba___ra_bka'),
		array('Olkusz, ulica Francesco Nullo','olkusz_ul_francesco_nullo'),
		array('Skawina, osiedle Ogrody','skawina_os_ogrody'),
		array('Szymbark','szymbark'),
		array('Trzebinia, osiedle Związku Walki Młodych','trzebinia_os_zwia_zku_walki_ml_odych'),
		array('Zakopane, ulica Sienkiewicza','zakopane_ul_sienkiewicza'),
		array('Szarów, ulica Spokojna','szaro_w_ul_spokojna'),
		array('Kaszów','kaszo_w'),
		array('Sucha Beskidzka, ulica Nieszczyńskiej','sucha_beskidzka_ul_nieszczyn_skiej'),
		array('Nowy Targ, Plac Słowackiego','nowy_targ_plac_sl_owackiego'),
		array('Warszawa-Komunikacyjna','warszawa_komunikacyjna'),
		array('Warszawa-Podleśna','warszawa_podles_na'),
		array('Warszawa-Tołstoja','warszawa_tol_stoja'),
		array('Warszawa-Marszałkowska','warszawa_marszal_kowska'),
		array('Warszawa-Ursynów','warszawa_ursyno_w'),
		array('Warszawa-Targówek','warszawa_targo_wek'),
		array('Płock-Gimnazjum','pl_ock_gimnazjum'),
		array('Płock-Reja','pl_ock_reja'),
		array('Radom-Tochtermana','radom_tochtermana'),
		array('Belsk-IGFPAN','belsk_igfpan'),
		array('Granica-KPN','granica_kpn'),
		array('Legionowo-Zegrzyńska','legionowo_zegrzyn_ska'),
		array('Piastów-Pułaskiego','piasto_w_pul_askiego'),
		array('Siedlce-Konarskiego','siedlce_konarskiego'),
		array('Lublin ulica Obywatelska','lublin_ul_obywatelska'),
		array('IMGW-Jarczew','imgw_jarczew'),
		array('Lublin-Podmiejska','lublin_podmiejska'),
		array('Zamość ulica Hrubieszowska 69A','zamos_c__ul_hrubieszowska_69a'),
		array('Gorzów Wlkp. ulica Kosynierów Gdyńskich','gorzo_w_wlkp_ul_kosyniero_w_gdyn_skich'),
		array('Zielona Góra ulica Krótka','zielona_go_ra_ul_kro_tka'),
		array('Smolary Bytnickie','smolary_bytnickie'),
		array('Sulęcin ulica Dudka','sule_cin_ul_dudka'),
		array('Wschowa ulica Kazimierza Wielkiego','wschowa_ul_kazimierza_wielkiego'),
		array('Żary, ulica Szymanowskiego 8','z_ary_ul_szymanowskiego_8'),
		array('Toruń Airpointer','torun__airpointer'),
		array('Toruń POLICJA','torun__policja'),
		array('Włocławek OKRZEI','wl_ocl_awek_okrzei'),
		array('Grudziądz Airpointer','grudzia_dz_airpointer'),
		array('Inowrocław Airpointer','inowrocl_aw_airpointer'),
		array('Ciechocinek','ciechocinek'),
		array('Koniczynka','koniczynka'),
		array('Bory Tucholskie','bory_tucholskie'),
);


    $slownikXXXX = array(
		array('zachmurzenie umiarkowane możliwe burze i opady deszczu','zachmurzenie_umiarkowane__mo_liwe_burze_i_opady_deszczu'),
		array('zachmurzenie umiarkowane możliwe burze','zachmurzenie_umiarkowane__mo_liwe_burze'),
		array('zachmurzenie umiarkowane z opadami deszczu','zachmurzenie_umiarkowane_z_opadami_deszczu'),
		array('pochmurno z opadami deszczu','pochmurno_z_opadami_deszczu'),
		array('czaniec kobiernice','czaniec_kobiernice'),
		array('las','las'),

    );



    $slownikXXX= array(
        array('Poziom promieniowania'),
        array('Poziom promieniowania gamma'),
        array('Poziom promieniowania jonizującego'),

        array('Wartość aktualna'),
        array('Średnia wartość dobowa'),

        array('mikrosjiwerta'),
        array('na godzinę'),

        array('setna'),
        array('setne'),
        array('setnych'),

        array('dziesiąta'),
        array('dziesiąte'),
        array('dziesiątych'),
    );

    $dslownikXXX = array(

        array('tu eksperymentalna automatyczna stacja pogodowa'),

        array('Stanisław Kłebek 9 adam tadeusz karol', 'sq9atk'),
        array('tu Stanisław Kłebek 9 adam tadeusz karol', 'tu_sq9atk'),

        array('stan pogody z dnia'),
        array('stan pogody z godziny'),
        array('małopolskiego','malopolskiego'),

        array('źródło','zrodlo'),
        array('komunikat specjalny od'),
        array('komunikat specjalny'),
        array('powtarzam komunikat'),

        array('pamiętaj'),
        array('wróg podsłuchuje'),

		#radioactive sq9atk
        array('Poziom promieniowania'),
        array('Poziom promieniowania gamma'),
        array('Poziom promieniowania jonizującego'),

        array('Wartość aktualna'),
        array('Średnia wartość dobowa'),

        array('mikrosjiwerta'),
        array('na godzinę'),

        array('setna'),
        array('setne'),
        array('setnych'),

        array('dziesiąta'),
        array('dziesiąte'),
        array('dziesiątych'),


        #geomagnetic sq9atk
        array('sytuacja geomagnetyczna w regionie'),

        array('po jutrze'),

        array('krótko po północy'),
        array('nad ranem'),
        array('rano'),
        array('przed południem'),
        array('wczesnym popołudniem'),
        array('po południu'),
        array('wieczorem'),
        array('przed północą'),

        array('brak istotnych zaburzeń geomagnetycznych'),
        array('lekkie zaburzenia geomagnetyczne'),
        array('umiarkowane zabużenia geomagnetyczne'),
        array('mała burza geomagnetyczna'),
        array('umiarkowana burza geomagnetyczna'),
        array('silna burza geomagnetyczna'),
        array('sztorm geomagnetyczny'),
        array('duży sztorm geomagnetyczny'),


        array('niezauważalne'),
        array('znikome'),
        array('lekkie'),
        array('podwyższone'),
        array('umiarkowane'),
        array('duże'),
        array('bardzo duże'),
        array('ekstremalne'),
        array('wahania dobowe'),




        # Sunrise SQ9ATK
        array('kalendarium'),
        array('wschód słońca'),
        array('zachód słońca'),
        array('kalendar zoznam sk'),


        #air pollution SQ9ATK
        array('Informacja o skażeniu powietrza'),
        array('mikrogram'),
        array('mikrogramy'),
        array('mikrogramów'),
        array('na metr sześcienny'),

        array('stacja pomiarowa Kraków'),
        array('stacja pomiarowa Nowy Sącz'),
        array('stacja pomiarowa Tarnów'),


        array('w normie','poziom_bardzo_dobry'),
        array('w normie','poziom_dobry'),
        array('lekkie skażenie','poziom_dostateczny'),
        array('umiarkowane skażenie','poziom_umiarkowany'),
        array('wysokie skażenie','poziom_zl_y'),
        array('bardzo wysokie skażenie','poziom_bardzo_zl_y'),

        array('aleja krasińskiego', 'al_krasin_skiego'),
        array('ulica bulwarowa', 'ul_bulwarowa'),
        array('ulica bujaka','ul_bujaka'),
        array('ulica dietla','ul_dietla'),
        array('osiedle Piastów','os_piasto_w'),
        array('ulica złoty róg','ul_zl_oty_ro_g'),

        array('pył pe em 10','pyl__pm10'),
        array('pył pe em 2.5','pyl__pm25'),
        array('dwutlenek azotu'),
        array('tlenek węgla'),
        array('dwutlenek siarki'),
        array('ozon'),


        # Sample dla wodowskazów
        array('rzeka'),
        array('wodowskaz'),
        array('stopień czuwania',    'stopien_czuwania'),
        array('stopień gotowości',   'stopien_gotowosci'),
        array('stopień zagrożenia',  'stopien_zagrozenia'),
        array('stopień ekstremalnych powodzi','stopien_ekstremalnych_powodzi'),
        array('iemgiewu', 'imgw'),
        array('komunikat hydrologiczny iemgiewu','komunikat_hydrologiczny_imgw'),
        array('meteoalarm eu'),

        array('lokalny komunikat hydrologiczny'),
        array('komunikat hydrologiczny'),
        array('przekroczenia stanów ostrzegawczych','przekroczenia stanow alarmowych'),
        array('przekroczenia stanów alarmowych','przekroczenia stanow ostrzegawczych'),

        array('promieniowanie tła'),
        array('przecinek', 'przecinek'),
        array('mikrosjiwerta na godzinę', 'mikrosiwerta_na_godzine'),
        array('w normie'),
        array('podwyższone'),
        array('wysokie'),

        // daty
        array('pierwszego'),
        array('drugiego'),
        array('trzeciego'),
        array('czwartego'),
        array('piątego','piatego'),
        array('szóstego','szostego'),
        array('siódmego','siodmego'),
        array('ósmego', 'osmego'),
        array('dziewiątego','dziewiatego'),
        array('dziesiątego','dziesiatego'),
        array('jedenastego'),
        array('dwunastego'),
        array('trzynastego'),
        array('czternastego'),
        array('piętnastego','pietnastego'),
        array('szesnastego'),
        array('siedemnastego'),
        array('osiemnastego'),
        array('dziewiętnastego','dziewietnastego'),
        array('dwudziestego'),
        array('trzydziestego'),


        // miesiące
        array('stycznia'),
        array('lutego'),
        array('marca'),
        array('kwietnia'),
        array('maja'),
        array('czerwca'),
        array('lipca'),
        array('sierpnia'),
        array('września','wrzesnia'),
        array('października','pazdziernika'),
        array('listopada'),
        array('grudnia'),

        #liczebniki
        array('pierwszy'),
        array('drugi'),
        array('trzeci'),
        array('czwarty'),
        array('piąty','piaty'),
        array('piąty najwyższy','piaty najwyzszy'),
        array('szósty','szosty'),
        array('siódmy','siodmy'),
        array('ósmy','osmy'),
        array('dziewiąty','dziewiaty'),
        array('dziesiąty','dziesiaty'),

        #liczby
        array('zero'),
        array('zero zero'),
        array('jeden'),
        array('dwa'),
        array('trzy'),
        array('cztery'),
        array('pięć','piec'),
        array('sześć','szesc'),
        array('siedem'),
        array('osiem'),
        array('dziewięć','dziewiec'),
        array('dziesięć','dziesiec'),
        array('jedenaście','jedenascie'),
        array('dwanaście','dwanascie'),
        array('trzynaście','trzynascie'),
        array('czternaście','czternascie'),
        array('piętnaście','pietnascie'),
        array('szesnaście','szesnascie'),
        array('siedemnaście','siedemnascie'),
        array('osiemnaście','osiemnascie'),
        array('dziewiętnaście','dziewietnascie'),
        array('dwadzieścia','dwadziescia'),
        array('trzydzieści','trzydziesci'),
        array('czterdzieści','czterdziesci'),
        array('pięćdziesiąt','piecdziesiat'),
        array('sześćdziesiąt','szescdziesiat'),
        array('siedemdziesiąt','siedemdziesiat'),
        array('osiemdziesiąt','osiemdziesiat'),
        array('dziewięćdziesiąt','dziewiecdziesiat'),
        array('sto'),
        array('dwieście','dwiescie'),
        array('trzysta',''),
        array('czterysta'),
        array('pięćset','piecset'),
        array('sześćset','szescset'),
        array('siedemset'),
        array('osiemset'),
        array('dziewięćset','dziewiecset'),
        array('tysiąc','tysiac'),
        array('tysiące','tysiace'),
        array('tysięcy','tysiecy'),

        #godziny
        array('pierwsza'),
        array('druga'),
        array('trzecia'),
        array('czwarta'),
        array('piąta','piata'),
        array('szósta','szosta'),
        array('siódma','siodma'),
        array('ósma','osma'),
        array('dziewiąta','dziewiata'),
        array('dziesiąta','dziesiata'),
        array('jedenasta'),
        array('dwunasta'),
        array('trzynasta'),
        array('czternasta'),
        array('piętnasta','pietnasta'),
        array('szesnasta'),
        array('siedemnasta'),
        array('osiemnasta'),
        array('dziewiętnasta','dziewietnasta'),
        array('dwudziesta'),

        # nazwy zjawisk pogodowych (dla Yahoo! Weather)
        array('bezchmurnie'),
        array('burza'),
        array('burza tropikalna'),
        array('deszcz'),
        array('deszcz i deszcz ze śniegiem','deszcz i deszcz ze sniegiem'),
        array('deszcz i grad'),
        array('deszcz ze śniegiem','deszcz ze sniegiem'),
        array('grad'),
        array('huragan'),
        array('marznący deszcz','marznacy deszcz'),
        array('pochmurno'),
        array('przelotne opady'),
        array('przelotne opady śniegu','przelotne opady sniegu'),
        array('przymrozki'),
        array('pył','pyl'),
        array('silne burze'),
        array('silny wiatr'),
        array('słabe zachmurzenie','slabe zachmurzenie'),
        array('słaby śnieg','slaby snieg'),
        array('smog'),
        array('śnieg','snieg'),
        array('śnieg i deszcz ze śniegiem','snieg i deszcz ze sniegiem'),
        array('tornado'),
        array('wietrznie'),
        array('zamglenia'),
        array('zawieje śnieżne','zawieje sniezne'),
        array('jahu łeder','y_weather'),

        ## różne
        array('temperatura'),
        array('stopień celsjusza','stopien celsjusza'),
        array('minus'),
        array('stopnie celsjusza'),
        array('stopni celsjusza'),
        array('kierunek wiatru'),
        array('północny','polnocny'),
        array('północno','polnocno'),
        array('wschodni','wschodni'),
        array('wschodnio'),
        array('zachodni'),
        array('zachodnio'),
        array('południowy','poludniowy'),
        array('południowo','poludniowo'),
        array('wilgotność','wilgotnosc'),
        array('procent'),
        array('prędkość wiatru','predkosc wiatru'),
        array('stopień','stopien'),
        array('stopnie'),
        array('stopni'),
        array('widoczność','widocznosc'),
        array('kilometr'),
        array('kilometry'),
        array('kilometrów','kilometrow'),
        array('prognoza na następne','prognoza na nastepne'),
        array('godzin'),array('godzina'),
        array('godziny'),
        array('z godziny'),
        array('temperatura od'),

        array('metr na sekundę','metr na sekunde'),
        array('metry na sekundę','metry na sekunde'),
        array('metrów na sekunde','metrow na sekunde'),
        array('kilometr na godzinę','kilometr na godzine'),
        array('kilometry na godzinę','kilometry na godzine'),
        array('kilometrów na godzinę','kilometrow na godzine'),

        array('ciśnienie','cisnienie'),
        array('hektopaskal'),
        array('hektopaskale'),
        array('hektopaskali'),
        array('tendencja spadkowa'),
        array('tendencja wzrostowa'),
        array('temperatura odczuwalna'),
        array('temperatura minimalna'),
        array('maksymalna'),
        array('następnie','nastepnie'),
        array('obowiązuje','obowiazuje'),

        #literowanie
        array('adam', 'a'),
        array('barbara', 'b'),
        array('celina', 'c'),
        array('dorota', 'd'),
        array('edward', 'e'),
        array('franciszek', 'f'),
        array('grażyna', 'g'),
        array('halina', 'h'),
        array('irena', 'i'),
        array('jadwiga', 'j'),
        array('karol', 'k'),
        array('ludwik', 'l'),
        array('maria', 'm'),
        array('natalia', 'n'),
        array('olga', 'o'),
        array('paweł', 'p'),
        array('kłebek', 'q'), # wł. Quebec
        array('roman', 'r'),
        array('stefan', 's'),
        array('tadeusz', 't'),
        array('urszula', 'u'),
        array('violetta', 'v'),
        array('wacław', 'w'),
        array('xawery', 'x'),
        array('ypsylon', 'y'), # wł. Ypsilon
        array('zygmunt', 'z'),
        array('łamane'),

        # Sample potrzebne dla modułu meteoalarm (cała Polska)
        array('zagrożenia meteorologiczne dla województwa', 'zagrozenia_meteorologiczne_dla_wojewodztwa'),
        array('mazowieckiego'),
        array('lubuskiego'),
        array('zachodniopomorskiego'),
        array('pomorskiego'),
        array('dolnośląskiego','dolnoslaskiego'),
        array('opolskiego'),
        array('śląskiego','slaskiego'),
        array('małopolskiego'),
        array('podkarpackiego'),
        array('świętokrzyskiego','swietokrzyskiego'),
        array('łódzkiego','lodzkiego'),
        array('wielkopolskiego'),
        array('kujawsko-pomorskiego'),
        array('warminsko-mazurskiego'),
        array('lubelskiego'),
        array('podlaskiego'),

        array('dziś','dzis'),
        array('jutro'),
        array('śnieg lub oblodzenie','snieg lub oblodzenie'),
        array('burze'),
        array('mgły','mgly'),
        array('niskie temperatury'),
        array('wysokie temperatury'),
        array('zjawiska strefy brzegowej'),
        array('pożary lasów','pozary lasow'),
        array('lawiny'),
        array('intensywne opady deszczu'),
        array('inne zagrożenia','inne zagrozenia'),
        array('poziom zagrożenia','poziom zagrozenia'),
        array('nieokreślony','nieokreslony'),
        array('niski'),
        array('średni','sredni'),
        array('wysoki'),



        array('burza śnieżna','burza sniezna'),
        array('częściowe zachmurzenie','czesciowe zachmurzenie'),
        array('zachmurzenie załkowite','zachmurzenie calkowite'),
        array('grad'),
        array('intensywne opady śniegu','intensywne opady sniegu'),
        array('lokalna przelotna marznąca mżawka','lokalna przelotna marznaca mzawka'),
        array('lokalne burze'),
        array('lokalne przelotne opady deszczu'),
        array('lokalny słaby deszcz','lokalny slaby deszcz'),
        array('marznąca mgła','marznaca mgla'),
        array('marznąca mżawka','marznaca mzawka'),
        array('mgła','mgla'),
        array('mżawka','mzawka'),
        array('opady śniegu','opady sniegu'),
        array('pochmurno'),
        array('przelotne opady deszczu'),
        array('przelotne ulewy'),
        array('słabe opady marznącego deszczu','slabe opady marznacego deszczu'),
        array('słabe opady śniegu','slabe opady sniegu'),
        array('słabe opady śniegu z deszczem','slabe opady sniegu z deszczem'),
        array('słabe opady śniegu ziarnistego','slabe opady sniegu ziarnistego'),
        array('słabe przelotne opady deszczu','slabe przelotne opady deszczu'),
        array('słaby deszcz','slaby deszcz'),
        array('śnieg','snieg'),
        array('śnieg z deszczem','snieg z deszczem'),
        array('ulewny deszcz'),
        array('ulewy'),
        array('umiarkowane lub ciężkie opady śniegu z deszczem','umiarkowane lub ciezkie opady sniegu z deszczem'),
        array('umiarkowane opady deszczu',''),
        array('umiarkowane opady marznącego deszczu','umiarkowane opady marznacego deszczu'),
        array('umiarkowane opady śniegu','umiarkowane opady sniegu'),
        array('umiarkowane opady śniegu z deszczem','umiarkowane opady sniegu z deszczem'),
        array('umiarkowane opady śniegu ziarnistego','umiarkowane opady sniegu ziarnistego'),
        array('zachmurzenie całkowite','zachmurzenie calkowite'),
        array('zamglenia'),
        array('zamieć śnieżna','zamiec sniezna'),
        array('pokrywa chmur'),
        array('łorld łeder onlajn','worldweatheronline'),
        array('stopien zagrozenia lawinowego'),
    );
