<?php
	$slownik = array(
		array('Annopol', 'annopol'),
		array('Babino', 'babino'),
		array('Balice', 'balice'),
		array('Banie Mazurskie', 'banie_mazurskie'),
		array('Barcinek', 'barcinek'),
		array('Bardo', 'bardo'),
		array('Bardy', 'bardy'),
		array('Bągart', 'ba_gart'),
		array('Biała Góra', 'bial_a_go_ra'),
		array('Biała Nyska', 'bial_a_nyska'),
		array('Białobrzeg Bliższy', 'bial_obrzeg_bliz_szy'),
		array('Białobrzegi', 'bial_obrzegi'),
		array('Białobrzezie', 'bial_obrzezie'),
		array('Białogard', 'bial_ogard'),
		array('Białogórzyno', 'bial_ogo_rzyno'),
		array('Białośliwie', 'bial_os_liwie'),
		array('Białowieża - Park', 'bial_owiez_a___park'),
		array('Bielawy', 'bielawy'),
		array('Bielinek', 'bielinek'),
		array('Bieruń Nowy', 'bierun__nowy'),
		array('Biłgoraj', 'bil_goraj'),
		array('Biskupice', 'biskupice'),
		array('Bledzew', 'bledzew'),
		array('Błażkowa', 'bl_az_kowa'),
		array('Bobry', 'bobry'),
		array('Bocheniec', 'bocheniec'),
		array('Bogatynia', 'bogatynia'),
		array('Bogdaj', 'bogdaj'),
		array('Bogdaszowice', 'bogdaszowice'),
		array('Bogusław', 'bogusl_aw'),
		array('Bojanów', 'bojano_w'),
		array('Bojszowy', 'bojszowy'),
		array('Bondary', 'bondary'),
		array('Borkowo', 'borkowo'),
		array('Bornity', 'bornity'),
		array('Borów', 'boro_w'),
		array('Borucino', 'borucino'),
		array('Borzęcin', 'borze_cin'),
		array('Bożepole Szlacheckie', 'boz_epole_szlacheckie'),
		array('Branice', 'branice'),
		array('Braniewo', 'braniewo'),
		array('Brańsk', 'bran_sk'),
		array('Brodnica', 'brodnica'),
		array('Brody Iłżeckie', 'brody_il_z_eckie'),
		array('Brody Pomorskie', 'brody_pomorskie'),
		array('Brynica', 'brynica'),
		array('Brzeg', 'brzeg'),
		array('Brzeg Dolny', 'brzeg_dolny'),
		array('Brzegi', 'brzegi'),
		array('Brzesko-Miasto (Lsop)', 'brzesko_miasto_lsop'),
		array('Brzeźnica', 'brzez_nica'),
		array('Bukowna', 'bukowna'),
		array('Bukówka', 'buko_wka'),
		array('Burzenin', 'burzenin'),
		array('Burzyn', 'burzyn'),
		array('Bystrzyca Kłodzka', 'bystrzyca_kl_odzka'),
		array('Bzin', 'bzin'),
		array('Chałupki', 'chal_upki'),
		array('Charnowo', 'charnowo'),
		array('Charytany', 'charytany'),
		array('Chełmno', 'chel_mno'),
		array('Chojnów', 'chojno_w'),
		array('Chraboły', 'chrabol_y'),
		array('Chwaliszów', 'chwaliszo_w'),
		array('Cieszyn', 'cieszyn'),
		array('Cięcina', 'cie_cina'),
		array('Ciężkowice', 'cie_z_kowice'),
		array('Cigacice', 'cigacice'),
		array('Cisna', 'cisna'),
		array('Czachy', 'czachy'),
		array('Czaniec-Kobiernice', 'czaniec_kobiernice'),
		array('Czarna Woda', 'czarna_woda'),
		array('Czarnków', 'czarnko_w'),
		array('Czarnowo', 'czarnowo'),
		array('Czchów', 'czcho_w'),
		array('Czechowice-Bestwina', 'czechowice_bestwina'),
		array('Czechowice-Dziedzice', 'czechowice_dziedzice'),
		array('Czekarzewice', 'czekarzewice'),
		array('Czernichów-Prom', 'czernicho_w_prom'),
		array('Daleszyce', 'daleszyce'),
		array('Darłowo', 'darl_owo'),
		array('Dąbie', 'da_bie'),
		array('Dąbrowa', 'da_browa'),
		array('Dąbrowa Bolesławiecka', 'da_browa_bolesl_awiecka'),
		array('Dębe', 'de_be'),
		array('Dęblin', 'de_blin'),
		array('Dębowo', 'de_bowo'),
		array('Dobczyce', 'dobczyce'),
		array('Dobra', 'dobra'),
		array('Dobroszów Wielki', 'dobroszo_w_wielki'),
		array('Dobrylas', 'dobrylas'),
		array('Dolna Kępa (Nowotki)', 'dolna_ke_pa_nowotki'),
		array('Domaradz', 'domaradz'),
		array('Dorohusk', 'dorohusk'),
		array('Drawiny', 'drawiny'),
		array('Drogomyśl', 'drogomys_l'),
		array('Dunino', 'dunino'),
		array('Dwernik', 'dwernik'),
		array('Dynów', 'dyno_w'),
		array('Działoszyn', 'dzial_oszyn'),
		array('Dzierżoniów', 'dzierz_onio_w'),
		array('Dziwnów', 'dziwno_w'),
		array('Elbląg', 'elbla_g'),
		array('Elgiszewo', 'elgiszewo'),
		array('Ełk ', 'el_k_'),
		array('Fasty', 'fasty'),
		array('Fordon', 'fordon'),
		array('Frankopol', 'frankopol'),
		array('Gdańsk Port Północny', 'gdan_sk_port_po_l_nocny'),
		array('Gdańsk Przegalina', 'gdan_sk_przegalina'),
		array('Gdańsk Sobieszewo', 'gdan_sk_sobieszewo'),
		array('Gdańsk Świbno', 'gdan_sk_s_wibno'),
		array('Gdańsk Ujście Wisły', 'gdan_sk_ujs_cie_wisl_y'),
		array('Gdańska Głowa (Drewnica)', 'gdan_ska_gl_owa_drewnica'),
		array('Gdynia', 'gdynia'),
		array('Giżycko', 'giz_ycko'),
		array('Gliwice', 'gliwice'),
		array('Gliwice-Łabędy', 'gliwice_l_abe_dy'),
		array('Głogów', 'gl_ogo_w'),
		array('Głowaczowa', 'gl_owaczowa'),
		array('Głuchołazy', 'gl_uchol_azy'),
		array('Gniechowice', 'gniechowice'),
		array('Goczałkowice', 'goczal_kowice'),
		array('Godowa', 'godowa'),
		array('Goleniów', 'golenio_w'),
		array('Gołdap 2', 'gol_dap_2'),
		array('Gołkowice', 'gol_kowice'),
		array('Goręczyno', 'gore_czyno'),
		array('Gorliczyna', 'gorliczyna'),
		array('Gorzów Śląski', 'gorzo_w_s_la_ski'),
		array('Gorzów Wielkopolski', 'gorzo_w_wielkopolski'),
		array('Gorzuchów', 'gorzucho_w'),
		array('Gościmiec', 'gos_cimiec'),
		array('Gozdowice', 'gozdowice'),
		array('Gozdów', 'gozdo_w'),
		array('Górki Wielkie', 'go_rki_wielkie'),
		array('Grabno', 'grabno'),
		array('Grabówka', 'grabo_wka'),
		array('Grębów', 'gre_bo_w'),
		array('Grudziądz', 'grudzia_dz'),
		array('Grybów', 'grybo_w'),
		array('Gryfino', 'gryfino'),
		array('Gryfów Śląski', 'gryfo_w_s_la_ski'),
		array('Grzegorzew', 'grzegorzew'),
		array('Gubin', 'gubin'),
		array('Gusin', 'gusin'),
		array('Harasimowicze', 'harasimowicze'),
		array('Harasiuki', 'harasiuki'),
		array('Hel', 'hel'),
		array('Hoczew', 'hoczew'),
		array('Iłowa', 'il_owa'),
		array('Iskrzynia', 'iskrzynia'),
		array('Istebna', 'istebna'),
		array('Izbica', 'izbica'),
		array('Jakubkowice', 'jakubkowice'),
		array('Jakuszyce', 'jakuszyce'),
		array('Januszewice', 'januszewice'),
		array('Jarnołtów', 'jarnol_to_w'),
		array('Jarnołtówek', 'jarnol_to_wek'),
		array('Jarosław', 'jarosl_aw'),
		array('Jasło', 'jasl_o'),
		array('Jawiszowice', 'jawiszowice'),
		array('Jawor', 'jawor'),
		array('Jelenia Góra', 'jelenia_go_ra'),
		array('Jeleń', 'jelen_'),
		array('Jordanów', 'jordano_w'),
		array('Jugowice', 'jugowice'),
		array('Jurkiszki', 'jurkiszki'),
		array('Kalisty', 'kalisty'),
		array('Kalnica', 'kalnica'),
		array('Kamesznica', 'kamesznica'),
		array('Kamieniec Ząbkowicki', 'kamieniec_za_bkowicki'),
		array('Kamienna Góra', 'kamienna_go_ra'),
		array('Kamionka', 'kamionka'),
		array('Kanclerzowice', 'kanclerzowice'),
		array('Karłowice', 'karl_owice'),
		array('Karpowicze', 'karpowicze'),
		array('Karsy', 'karsy'),
		array('Kasinka Mała', 'kasinka_mal_a'),
		array('Kazanów', 'kazano_w'),
		array('Kępa Polska', 'ke_pa_polska'),
		array('Kęszyce', 'ke_szyce'),
		array('Klęczany', 'kle_czany'),
		array('Kłodzko', 'kl_odzko'),
		array('Kłudzice', 'kl_udzice'),
		array('Koło', 'kol_o'),
		array('Kołobrzeg', 'kol_obrzeg'),
		array('Konin-Morzysław', 'konin_morzysl_aw'),
		array('Koniówka', 'konio_wka'),
		array('Kopice', 'kopice'),
		array('Koprzywnica', 'koprzywnica'),
		array('Korzeńsko', 'korzen_sko'),
		array('Korzybie', 'korzybie'),
		array('Kostrzyn Nad Odrą', 'kostrzyn_nad_odra_'),
		array('Koszyce Wielkie', 'koszyce_wielkie'),
		array('Kościan', 'kos_cian'),
		array('Kościelec', 'kos_cielec'),
		array('Kościelisko-Kiry', 'kos_cielisko_kiry'),
		array('Kośmin', 'kos_min'),
		array('Kowanówko', 'kowano_wko'),
		array('Kowary', 'kowary'),
		array('Kozłowa Góra', 'kozl_owa_go_ra'),
		array('Koźle', 'koz_le'),
		array('Krajowice', 'krajowice'),
		array('Kraków-Bielany', 'krako_w_bielany'),
		array('Krapkowice', 'krapkowice'),
		array('Krasków', 'krasko_w'),
		array('Krasnystaw', 'krasnystaw'),
		array('Kraszewice', 'kraszewice'),
		array('Krąplewice', 'kra_plewice'),
		array('Krempna-Kotań', 'krempna_kotan_'),
		array('Kręciwilk', 'kre_ciwilk'),
		array('Krosno', 'krosno'),
		array('Krościenko', 'kros_cienko'),
		array('Krówniki', 'kro_wniki'),
		array('Krubice', 'krubice'),
		array('Krupski Młyn', 'krupski_ml_yn'),
		array('Kryłów', 'kryl_o_w'),
		array('Krzczonów', 'krzczono_w'),
		array('Krzyczew', 'krzyczew'),
		array('Krzywa Góra', 'krzywa_go_ra'),
		array('Krzyż', 'krzyz_'),
		array('Krzyżanowice', 'krzyz_anowice'),
		array('Kudowa-Zdrój-Zakrze', 'kudowa_zdro_j_zakrze'),
		array('Kule', 'kule'),
		array('Kulesze Chobotki', 'kulesze_chobotki'),
		array('Kuligi', 'kuligi'),
		array('Kunów', 'kuno_w'),
		array('Kuźnica Skakawska', 'kuz_nica_skakawska'),
		array('Kuźnica Sulikowska', 'kuz_nica_sulikowska'),
		array('Kwiatkówek', 'kwiatko_wek'),
		array('Kwidzyn', 'kwidzyn'),
		array('Las', 'las'),
		array('Ląd', 'la_d'),
		array('Lądek-Zdrój', 'la_dek_zdro_j'),
		array('Lenartowice', 'lenartowice'),
		array('Lesko', 'lesko'),
		array('Leśna', 'les_na'),
		array('Leżachów', 'lez_acho_w'),
		array('Lębork 2', 'le_bork_2'),
		array('Lgota Nadwarcie', 'lgota_nadwarcie'),
		array('Lidzbark', 'lidzbark'),
		array('Lipnica Murowana (Lsop)', 'lipnica_murowana_lsop'),
		array('Lubachów', 'lubacho_w'),
		array('Lubartów', 'lubarto_w'),
		array('Lubień', 'lubien_'),
		array('Ludźmierz', 'ludz_mierz'),
		array('Lutomiersk', 'lutomiersk'),
		array('Łabowa', 'l_abowa'),
		array('Łabuzie', 'l_abuzie'),
		array('Łagisza', 'l_agisza'),
		array('Łapanów-Rynek (Lsop)', 'l_apano_w_rynek_lsop'),
		array('Łask', 'l_ask'),
		array('Łaziska', 'l_aziska'),
		array('Łażany', 'l_az_any'),
		array('Łąki', 'l_a_ki'),
		array('Łeba', 'l_eba'),
		array('Łękawica', 'l_e_kawica'),
		array('Łochów', 'l_ocho_w'),
		array('Łodygowice', 'l_odygowice'),
		array('Łomnica', 'l_omnica'),
		array('Łozy', 'l_ozy'),
		array('Łupawa', 'l_upawa'),
		array('Łysa Polana', 'l_ysa_polana'),
		array('Maków Mazowiecki', 'mako_w_mazowiecki'),
		array('Malczyce', 'malczyce'),
		array('Maldanin', 'maldanin'),
		array('Malowa Góra', 'malowa_go_ra'),
		array('Małkinia', 'mal_kinia'),
		array('Michalów', 'michalo_w'),
		array('Michałów', 'michal_o_w'),
		array('Mieduniszki', 'mieduniszki'),
		array('Mielec 2', 'mielec_2'),
		array('Mietków', 'mietko_w'),
		array('Międzychód', 'mie_dzycho_d'),
		array('Międzylesie', 'mie_dzylesie'),
		array('Mikuszowice', 'mikuszowice'),
		array('Miłoszewo', 'mil_oszewo'),
		array('Mirków', 'mirko_w'),
		array('Mirsk', 'mirsk'),
		array('Mizerów-Borki', 'mizero_w_borki'),
		array('Mniszek', 'mniszek'),
		array('Mocha', 'mocha'),
		array('Modlin', 'modlin'),
		array('Morawica', 'morawica'),
		array('Mosina', 'mosina'),
		array('Mościsko', 'mos_cisko'),
		array('Mszana Dolna', 'mszana_dolna'),
		array('Muszyna Milik', 'muszyna_milik'),
		array('Nakło-Zachód', 'nakl_o_zacho_d'),
		array('Namysłów', 'namysl_o_w'),
		array('Narew', 'narew'),
		array('Narewka', 'narewka'),
		array('Niechmirów', 'niechmiro_w'),
		array('Niedzica', 'niedzica'),
		array('Nielisz', 'nielisz'),
		array('Niemodlin', 'niemodlin'),
		array('Nienowice', 'nienowice'),
		array('Nietków', 'nietko_w'),
		array('Nietulisko Duże', 'nietulisko_duz_e'),
		array('Nisko', 'nisko'),
		array('Niwka', 'niwka'),
		array('Niwki', 'niwki'),
		array('Nowa Pasłęka', 'nowa_pasl_e_ka'),
		array('Nowa Sól', 'nowa_so_l'),
		array('Nowa Wieś Podgórna', 'nowa_wies__podgo_rna'),
		array('Nowe Batorowo (Nowakowo)', 'nowe_batorowo_nowakowo'),
		array('Nowe Drezdenko', 'nowe_drezdenko'),
		array('Nowe Miasto', 'nowe_miasto'),
		array('Nowe Miasto Lubawskie', 'nowe_miasto_lubawskie'),
		array('Nowe Sadłuki', 'nowe_sadl_uki'),
		array('Nowogrodziec', 'nowogrodziec'),
		array('Nowogród', 'nowogro_d'),
		array('Nowogród Bobrzański', 'nowogro_d_bobrzan_ski'),
		array('Nowosielce', 'nowosielce'),
		array('Nowosiółki', 'nowosio_l_ki'),
		array('Nowy Dwór Gdański', 'nowy_dwo_r_gdan_ski'),
		array('Nowy Sącz_Dunajec', 'nowy_sa_cz_dunajec'),
		array('Nowy Sącz_Kamienica', 'nowy_sa_cz_kamienica'),
		array('Nowy Sącz_Łubinka', 'nowy_sa_cz_l_ubinka'),
		array('Nowy Targ', 'nowy_targ'),
		array('Nowy Targ-Kowaniec', 'nowy_targ_kowaniec'),
		array('Nysa', 'nysa'),
		array('Oborniki', 'oborniki'),
		array('Odolanów', 'odolano_w'),
		array('Odrzywół', 'odrzywo_l_'),
		array('Ojców', 'ojco_w'),
		array('Okocim (Lsop)', 'okocim_lsop'),
		array('Olchowce', 'olchowce'),
		array('Olsztyn-Kortowo', 'olsztyn_kortowo'),
		array('Olza', 'olza'),
		array('Oława', 'ol_awa'),
		array('Ołobok', 'ol_obok'),
		array('Opole-Groszowice', 'opole_groszowice'),
		array('Orzechowo', 'orzechowo'),
		array('Osetno', 'osetno'),
		array('Osielec', 'osielec'),
		array('Osjaków', 'osjako_w'),
		array('Osłonka', 'osl_onka'),
		array('Osowiec ', 'osowiec_'),
		array('Ostrołęka', 'ostrol_e_ka'),
		array('Ostróda', 'ostro_da'),
		array('Ostróżno', 'ostro_z_no'),
		array('Osuchy', 'osuchy'),
		array('Oświęcim', 'os_wie_cim'),
		array('Ozimek', 'ozimek'),
		array('Pakość', 'pakos_c_'),
		array('Pasłęk', 'pasl_e_k'),
		array('Pewel Mała', 'pewel_mal_a'),
		array('Piaseczno 2', 'piaseczno_2'),
		array('Piątnica', 'pia_tnica'),
		array('Piątnica-Łomża', 'pia_tnica_l_omz_a'),
		array('Piechowice', 'piechowice'),
		array('Pierzchały ', 'pierzchal_y_'),
		array('Pierzchały_2', 'pierzchal_y_2'),
		array('Pilchowice', 'pilchowice'),
		array('Piła', 'pil_a'),
		array('Pińczów', 'pin_czo_w'),
		array('Pisz', 'pisz'),
		array('Piwonice', 'piwonice'),
		array('Piwoń', 'piwon_'),
		array('Pleśno', 'ples_no'),
		array('Ploski', 'ploski'),
		array('Poddębice', 'podde_bice'),
		array('Podgórze', 'podgo_rze'),
		array('Podgórzyn', 'podgo_rzyn'),
		array('Podkępie', 'podke_pie'),
		array('Polana', 'polana'),
		array('Połaniec', 'pol_aniec'),
		array('Połęcko', 'pol_e_cko'),
		array('Popędzynka', 'pope_dzynka'),
		array('Popowo', 'popowo'),
		array('Poraj', 'poraj'),
		array('Porajów', 'porajo_w'),
		array('Poronin', 'poronin'),
		array('Posoka', 'posoka'),
		array('Poznań-Most Rocha', 'poznan__most_rocha'),
		array('Prosna', 'prosna'),
		array('Prostki', 'prostki'),
		array('Proszówki', 'proszo_wki'),
		array('Prudnik', 'prudnik'),
		array('Pruszcz Gdański', 'pruszcz_gdan_ski'),
		array('Pruszcz Gdański Kanał', 'pruszcz_gdan_ski_kanal_'),
		array('Prynowo', 'prynowo'),
		array('Przechody', 'przechody'),
		array('Przeczyce', 'przeczyce'),
		array('Przedbórz', 'przedbo_rz'),
		array('Przemyśl', 'przemys_l'),
		array('Przewoźniki', 'przewoz_niki'),
		array('Przewóz', 'przewo_z'),
		array('Przystań', 'przystan_'),
		array('Pszczyna', 'pszczyna'),
		array('Ptaki', 'ptaki'),
		array('Ptusza', 'ptusza'),
		array('Puck', 'puck'),
		array('Puławy', 'pul_awy'),
		array('Puławy-Azoty', 'pul_awy_azoty'),
		array('Pustków', 'pustko_w'),
		array('Pustynia', 'pustynia'),
		array('Pyskowice', 'pyskowice'),
		array('Pyskowice-Dzierżno', 'pyskowice_dzierz_no'),
		array('Pyzdry', 'pyzdry'),
		array('Rabka 2', 'rabka_2'),
		array('Racibórz-Miedonia', 'racibo_rz_miedonia'),
		array('Racławice Śląskie', 'racl_awice_s_la_skie'),
		array('Radocha', 'radocha'),
		array('Radomyśl', 'radomys_l'),
		array('Radziszów', 'radziszo_w'),
		array('Rajcza', 'rajcza'),
		array('Rajgród ', 'rajgro_d_'),
		array('Raków', 'rako_w'),
		array('Resko', 'resko'),
		array('Ręczyn', 're_czyn'),
		array('Rodzone', 'rodzone'),
		array('Rogożek', 'rogoz_ek'),
		array('Rogóźno', 'rogo_z_no'),
		array('Rogóźno 2', 'rogo_z_no_2'),
		array('Ropa', 'ropa'),
		array('Ruda Jastkowska', 'ruda_jastkowska'),
		array('Ruda Kozielska', 'ruda_kozielska'),
		array('Rudze', 'rudze'),
		array('Rybnik-Gotartowice', 'rybnik_gotartowice'),
		array('Rybnik-Stodoły', 'rybnik_stodol_y'),
		array('Rybotycze', 'rybotycze'),
		array('Rydzyna', 'rydzyna'),
		array('Rzepin', 'rzepin'),
		array('Rzeszotary', 'rzeszotary'),
		array('Rzeszów', 'rzeszo_w'),
		array('Rzuchów', 'rzucho_w'),
		array('Rzymówka', 'rzymo_wka'),
		array('Samarzewo', 'samarzewo'),
		array('Sandomierz', 'sandomierz'),
		array('Santok', 'santok'),
		array('Sarzyna', 'sarzyna'),
		array('Sępopol', 'se_popol'),
		array('Siemianówka', 'siemiano_wka'),
		array('Sieniawa', 'sieniawa'),
		array('Sieniawka', 'sieniawka'),
		array('Sieradz', 'sieradz'),
		array('Sierosławice', 'sierosl_awice'),
		array('Skawica Dolna', 'skawica_dolna'),
		array('Skoczów', 'skoczo_w'),
		array('Skorogoszcz', 'skorogoszcz'),
		array('Skwierzyna', 'skwierzyna'),
		array('Sławsk', 'sl_awsk'),
		array('Słowik', 'sl_owik'),
		array('Słubice', 'sl_ubice'),
		array('Słupsk', 'sl_upsk'),
		array('Smolajny', 'smolajny'),
		array('Smolice', 'smolice'),
		array('Smołdzino', 'smol_dzino'),
		array('Smukała', 'smukal_a'),
		array('Sobianowice', 'sobianowice'),
		array('Sochonie', 'sochonie'),
		array('Sokołda', 'sokol_da'),
		array('Sosnówka', 'sosno_wka'),
		array('Soszyca', 'soszyca'),
		array('Spała', 'spal_a'),
		array('Sromowce Wyżne', 'sromowce_wyz_ne'),
		array('Staniszcze Wielkie', 'staniszcze_wielkie'),
		array('Stargard', 'stargard'),
		array('Stary Kraków', 'stary_krako_w'),
		array('Stary Raduszec', 'stary_raduszec'),
		array('Stary Sącz', 'stary_sa_cz'),
		array('Staszów', 'staszo_w'),
		array('Stradomka', 'stradomka'),
		array('Strękowa Góra', 'stre_kowa_go_ra'),
		array('Stróża', 'stro_z_a'),
		array('Strzyżów', 'strzyz_o_w'),
		array('Stuposiany', 'stuposiany'),
		array('Sucha Beskidzka', 'sucha_beskidzka'),
		array('Suchy Dąb', 'suchy_da_b'),
		array('Sulejów (Kopalnia)', 'sulejo_w_kopalnia'),
		array('Supraśl', 'supras_l'),
		array('Suraż', 'suraz_'),
		array('Szabelnia', 'szabelnia'),
		array('Szaflary', 'szaflary'),
		array('Szalejów Dolny', 'szalejo_w_dolny'),
		array('Szczawne', 'szczawne'),
		array('Szczecin Most Długi', 'szczecin_most_dl_ugi'),
		array('Szczecin Podjuchy', 'szczecin_podjuchy'),
		array('Szczerców', 'szczerco_w'),
		array('Szczucin', 'szczucin'),
		array('Szkwa', 'szkwa'),
		array('Szprotawa', 'szprotawa'),
		array('Szreńsk', 'szren_sk'),
		array('Sztabin', 'sztabin'),
		array('Szypry', 'szypry'),
		array('Ścinawa', 's_cinawa'),
		array('Ślęza', 's_le_za'),
		array('Śrem', 's_rem'),
		array('Świebodzice', 's_wiebodzice'),
		array('Świerkocin', 's_wierkocin'),
		array('Świerzawa', 's_wierzawa'),
		array('Świnoujście', 's_winoujs_cie'),
		array('Tchórzew', 'tcho_rzew'),
		array('Tczew', 'tczew'),
		array('Terka', 'terka'),
		array('Tłumaczów', 'tl_umaczo_w'),
		array('Tokarnia', 'tokarnia'),
		array('Tolkmicko', 'tolkmicko'),
		array('Tomaryny', 'tomaryny'),
		array('Topoliny', 'topoliny'),
		array('Toruń', 'torun_'),
		array('Trawniki', 'trawniki'),
		array('Trąbczyn', 'tra_bczyn'),
		array('Trestno', 'trestno'),
		array('Trybsz 2', 'trybsz_2'),
		array('Tryńcza', 'tryn_cza'),
		array('Trzciniec', 'trzciniec'),
		array('Trzebiatów', 'trzebiato_w'),
		array('Trzebież', 'trzebiez_'),
		array('Tuchola', 'tuchola'),
		array('Tujsk', 'tujsk'),
		array('Turawa', 'turawa'),
		array('Turoszów', 'turoszo_w'),
		array('Tychówko', 'tycho_wko'),
		array('Tylmanowa', 'tylmanowa'),
		array('Ujsoły', 'ujsol_y'),
		array('Ujście', 'ujs_cie'),
		array('Ujście Nysy Kłodzkiej', 'ujs_cie_nysy_kl_odzkiej'),
		array('Uniejów', 'uniejo_w'),
		array('Ustka', 'ustka'),
		array('Ustroń-Obłaziec', 'ustron__obl_aziec'),
		array('Wadowice', 'wadowice'),
		array('Walery', 'walery'),
		array('Wampierzów', 'wampierzo_w'),
		array('Warszawa', 'warszawa'),
		array('Warszawa-Nadwilanówka Śl', 'warszawa_nadwilano_wka_s_l'),
		array('Wąchock', 'wa_chock'),
		array('Wąsosz', 'wa_sosz'),
		array('Wejherowo', 'wejherowo'),
		array('Węgorzewo', 'we_gorzewo'),
		array('Widawa', 'widawa'),
		array('Widuchowa', 'widuchowa'),
		array('Wilkanów', 'wilkano_w'),
		array('Winnica', 'winnica'),
		array('Wisła', 'wisl_a'),
		array('Wisła-Czarne', 'wisl_a_czarne'),
		array('Wisła-Czarne (Biała Wisełka)', 'wisl_a_czarne_bial_a_wisel_ka'),
		array('Wisła-Czarne (Czarna Wisełka)', 'wisl_a_czarne_czarna_wisel_ka'),
		array('Wiślina', 'wis_lina'),
		array('Wizna', 'wizna'),
		array('Władysławowo', 'wl_adysl_awowo'),
		array('Włochy', 'wl_ochy'),
		array('Włocławek', 'wl_ocl_awek'),
		array('Włodawa', 'wl_odawa'),
		array('Wojanów', 'wojano_w'),
		array('Wolin', 'wolin'),
		array('Wólka Mlądzka', 'wo_lka_mla_dzka'),
		array('Wronki', 'wronki'),
		array('Wychódźc', 'wycho_dz_c'),
		array('Wyrzysk', 'wyrzysk'),
		array('Wyszków', 'wyszko_w'),
		array('Wyszogród', 'wyszogro_d'),
		array('Zabrzeg', 'zabrzeg'),
		array('Zabuże', 'zabuz_e'),
		array('Zagórz', 'zago_rz'),
		array('Zagrodno', 'zagrodno'),
		array('Zakłodzie', 'zakl_odzie'),
		array('Zakopane-Harenda', 'zakopane_harenda'),
		array('Zaliwie-Piegawki', 'zaliwie_piegawki'),
		array('Zambski Kościelne', 'zambski_kos_cielne'),
		array('Zapałów', 'zapal_o_w'),
		array('Zaruzie', 'zaruzie'),
		array('Zator', 'zator'),
		array('Zatwarnica', 'zatwarnica'),
		array('Zawady', 'zawady'),
		array('Zawady ', 'zawady_'),
		array('Zawichost', 'zawichost'),
		array('Zboiska', 'zboiska'),
		array('Zborowice', 'zborowice'),
		array('Zbytowa', 'zbytowa'),
		array('Zgłobice', 'zgl_obice'),
		array('Zgorzelec', 'zgorzelec'),
		array('Żabnica', 'z_abnica'),
		array('Żabno', 'z_abno'),
		array('Żagań', 'z_agan_'),
		array('Żarnowa', 'z_arnowa'),
		array('Żelazno', 'z_elazno'),
		array('Żółków', 'z_o_l_ko_w'),
		array('Żukowo', 'z_ukowo'),
		array('Żuków', 'z_uko_w'),
		array('Żywiec', 'z_ywiec'),
	);
