<?php

$slownik = array(
    array('Barycz', 'barycz'),
    array('Bauda', 'bauda'),
    array('Bawół', 'bawo_l_'),
    array('Bałtyk', 'bal_tyk'),
    array('Biała', 'bial_a'),
    array('Biała Głuchołaska', 'bial_a_gl_uchol_aska'),
    array('Biała Lądecka', 'bial_a_la_decka'),
    array('Biała Przemsza', 'bial_a_przemsza'),
    array('Biała Wisełka', 'bial_a_wisel_ka'),
    array('Białka', 'bial_ka'),
    array('Biały Dunajec', 'bial_y_dunajec'),
    array('Biebrza', 'biebrza'),
    array('Bielawa', 'bielawa'),
    array('Bierawka', 'bierawka'),
    array('Bobrza', 'bobrza'),
    array('Boczne Koryto Opawy', 'boczne_koryto_opawy'),
    array('Bogacica', 'bogacica'),
    array('Brda', 'brda'),
    array('Brennica', 'brennica'),
    array('Breń', 'bren_'),
    array('Brynica', 'brynica'),
    array('Brzeźnica', 'brzez_nica'),
    array('Brzozówka', 'brzozo_wka'),
    array('Budkowiczanka', 'budkowiczanka'),
    array('Budzówka', 'budzo_wka'),
    array('Bug', 'bug'),
    array('Bukowa', 'bukowa'),
    array('Bystra', 'bystra'),
    array('Bystrzyca', 'bystrzyca'),
    array('Bystrzyca Dusznicka', 'bystrzyca_dusznicka'),
    array('Bzura', 'bzura'),
    array('Bóbr', 'bo_br'),
    array('Cieśnina Dziwna', 'cies_nina_dziwna'),
    array('Czarna', 'czarna'),
    array('Czarna Nida', 'czarna_nida'),
    array('Czarna Woda', 'czarna_woda'),
    array('Czarny Dunajec', 'czarny_dunajec'),
    array('Czarny Potok', 'czarny_potok'),
    array('Czerna Mała', 'czerna_mal_a'),
    array('Czerna Wielka', 'czerna_wielka'),
    array('Czerwona Woda', 'czerwona_woda'),
    array('Drama', 'drama'),
    array('Drawa', 'drawa'),
    array('Drwęca', 'drwe_ca'),
    array('Drwęca Warmińska', 'drwe_ca_warmin_ska'),
    array('Drzewiczka', 'drzewiczka'),
    array('Dunajec', 'dunajec'),
    array('Elbląg', 'elbla_g'),
    array('Ełk', 'el_k'),
    array('Gostynia', 'gostynia'),
    array('Gołdapa', 'gol_dapa'),
    array('Grabia', 'grabia'),
    array('Grabinka', 'grabinka'),
    array('Guber', 'guber'),
    array('Gwda', 'gwda'),
    array('Hoczewka', 'hoczewka'),
    array('Huczwa', 'huczwa'),
    array('Ina', 'ina'),
    array('Iłownica', 'il_ownica'),
    array('Iłżanka', 'il_z_anka'),
    array('Jasiołka', 'jasiol_ka'),
    array('Jedlica', 'jedlica'),
    array('Jegrznia', 'jegrznia'),
    array('Jez. Druzno', 'jez._druzno'),
    array('Jez. Drwęckie', 'jez._drwe_ckie'),
    array('Jez. Ełckie', 'jez._el_ckie'),
    array('Jez. Mamry', 'jez._mamry'),
    array('Jez. Raduńskie Górne', 'jez._radun_skie_go_rne'),
    array('Jez. Rajgrodzkie', 'jez._rajgrodzkie'),
    array('Jez. Roś', 'jez._ros_'),
    array('Jez. Wadąg', 'jez._wada_g'),
    array('Jez. Łebsko', 'jez._l_ebsko'),
    array('Jeziorka', 'jeziorka'),
    array('Kaczawa', 'kaczawa'),
    array('Kamienica', 'kamienica'),
    array('Kamienna', 'kamienna'),
    array('Kanał Mosiński', 'kanal__mosin_ski'),
    array('Kanał Raduński', 'kanal__radun_ski'),
    array('Kanał Ślesiński', 'kanal__s_lesin_ski'),
    array('Kiełbaska', 'kiel_baska'),
    array('Kirowa Woda', 'kirowa_woda'),
    array('Klikawa', 'klikawa'),
    array('Koprzywianka', 'koprzywianka'),
    array('Koszarawa', 'koszarawa'),
    array('Krzczonówka', 'krzczono_wka'),
    array('Krzna', 'krzna'),
    array('Kuroch', 'kuroch'),
    array('Kwisa', 'kwisa'),
    array('Kłodnica', 'kl_odnica'),
    array('Lepietnica', 'lepietnica'),
    array('Liswarta', 'liswarta'),
    array('Liwa', 'liwa'),
    array('Liwiec', 'liwiec'),
    array('Lubaczówka', 'lubaczo_wka'),
    array('Lubieńka', 'lubien_ka'),
    array('Lubsza', 'lubsza'),
    array('Luciąża', 'lucia_z_a'),
    array('Martwa Wisła', 'martwa_wisl_a'),
    array('Mała Panew', 'mal_a_panew'),
    array('Miedzianka', 'miedzianka'),
    array('Mierzawa', 'mierzawa'),
    array('Mitręga', 'mitre_ga'),
    array('Mleczka', 'mleczka'),
    array('Morwawa', 'morwawa'),
    array('Motława', 'motl_awa'),
    array('Mroga', 'mroga'),
    array('Mszanka', 'mszanka'),
    array('Mławka', 'ml_awka'),
    array('Młynówka', 'ml_yno_wka'),
    array('Narew', 'narew'),
    array('Narewka', 'narewka'),
    array('Ner', 'ner'),
    array('Nereśl', 'neres_l'),
    array('Netta', 'netta'),
    array('Nida', 'nida'),
    array('Nieciecz', 'nieciecz'),
    array('Niedziczanka', 'niedziczanka'),
    array('Niesób', 'nieso_b'),
    array('Nogat', 'nogat'),
    array('Noteć', 'notec_'),
    array('Nurzec', 'nurzec'),
    array('Nysa Kłodzka', 'nysa_kl_odzka'),
    array('Nysa Szalona', 'nysa_szalona'),
    array('Nysa Łużycka', 'nysa_l_uz_ycka'),
    array('Obra', 'obra'),
    array('Ochotnica', 'ochotnica'),
    array('Odra', 'odra'),
    array('Oleśnica', 'oles_nica'),
    array('Olza', 'olza'),
    array('Omulew', 'omulew'),
    array('Opawa', 'opawa'),
    array('Orla', 'orla'),
    array('Orlanka', 'orlanka'),
    array('Orz', 'orz'),
    array('Orzyc', 'orzyc'),
    array('Osa', 'osa'),
    array('Osobłoga', 'osobl_oga'),
    array('Osława', 'osl_awa'),
    array('Oława', 'ol_awa'),
    array('Ołobok', 'ol_obok'),
    array('Parsęta', 'parse_ta'),
    array('Pasłęka', 'pasl_e_ka'),
    array('Pełcznica', 'pel_cznica'),
    array('Pielnica', 'pielnica'),
    array('Pilica', 'pilica'),
    array('Pisa', 'pisa'),
    array('Piława', 'pil_awa'),
    array('Podgórna', 'podgo_rna'),
    array('Pokrzywianka', 'pokrzywianka'),
    array('Polska Woda', 'polska_woda'),
    array('Polski Rów', 'polski_ro_w'),
    array('Poprad', 'poprad'),
    array('Poroniec', 'poroniec'),
    array('Powa', 'powa'),
    array('Prosna', 'prosna'),
    array('Prudnik', 'prudnik'),
    array('Przemsza', 'przemsza'),
    array('Prądnik', 'pra_dnik'),
    array('Psina', 'psina'),
    array('Pszczynka', 'pszczynka'),
    array('Pór', 'po_r'),
    array('Raba', 'raba'),
    array('Radew', 'radew'),
    array('Radomka', 'radomka'),
    array('Radunia', 'radunia'),
    array('Rawka', 'rawka'),
    array('Reda', 'reda'),
    array('Rega', 'rega'),
    array('Rgilewka', 'rgilewka'),
    array('Ropa', 'ropa'),
    array('Rozoga', 'rozoga'),
    array('Ruda', 'ruda'),
    array('Rudawa', 'rudawa'),
    array('Ruż', 'ruz_'),
    array('San', 'san'),
    array('Sidra', 'sidra'),
    array('Skawa', 'skawa'),
    array('Skawica', 'skawica'),
    array('Skawinka', 'skawinka'),
    array('Skora', 'skora'),
    array('Skroda', 'skroda'),
    array('Sokołda', 'sokol_da'),
    array('Solinka', 'solinka'),
    array('Soła', 'sol_a'),
    array('Sośniak', 'sos_niak'),
    array('Stobnica', 'stobnica'),
    array('Stobrawa', 'stobrawa'),
    array('Stradomka', 'stradomka'),
    array('Stradunia', 'stradunia'),
    array('Stryszawka', 'stryszawka'),
    array('Strzegomka', 'strzegomka'),
    array('Supraśl', 'supras_l'),
    array('Swędrnia', 'swe_drnia'),
    array('Szkarpawa', 'szkarpawa'),
    array('Szkwa', 'szkwa'),
    array('Szkło', 'szkl_o'),
    array('Szprotawa', 'szprotawa'),
    array('Szreniawa', 'szreniawa'),
    array('Sąsiecznica', 'sa_siecznica'),
    array('Słupia', 'sl_upia'),
    array('Tanew', 'tanew'),
    array('Trzebośnica', 'trzebos_nica'),
    array('Tuja', 'tuja'),
    array('Tyśmienica', 'tys_mienica'),
    array('Uszwica', 'uszwica'),
    array('Utrata', 'utrata'),
    array('Wapienica', 'wapienica'),
    array('Warta', 'warta'),
    array('Wałsza', 'wal_sza'),
    array('Wda', 'wda'),
    array('Wel', 'wel'),
    array('Wetlina', 'wetlina'),
    array('Wełna', 'wel_na'),
    array('Wiar', 'wiar'),
    array('Widawa', 'widawa'),
    array('Widawka', 'widawka'),
    array('Wielki Rogoźnik', 'wielki_rogoz_nik'),
    array('Wieprz', 'wieprz'),
    array('Wieprza', 'wieprza'),
    array('Wieprzówka', 'wieprzo_wka'),
    array('Wierna Rzeka', 'wierna_rzeka'),
    array('Wierzyca', 'wierzyca'),
    array('Wilczka', 'wilczka'),
    array('Wissa', 'wissa'),
    array('Wisznia', 'wisznia'),
    array('Wisła', 'wisl_a'),
    array('Wisłok', 'wisl_ok'),
    array('Wisłoka', 'wisl_oka'),
    array('Witka', 'witka'),
    array('Wkra', 'wkra'),
    array('Woda Ujsolska', 'woda_ujsolska'),
    array('Wołosaty', 'wol_osaty'),
    array('Wrześnica', 'wrzes_nica'),
    array('Wąska', 'wa_ska'),
    array('Węgorapa', 'we_gorapa'),
    array('Zalew Szczeciński', 'zalew_szczecin_ski'),
    array('Zalew Wiślany', 'zalew_wis_lany'),
    array('Złoty Potok', 'zl_oty_potok'),
    array('Łada', 'l_ada'),
    array('Łagowianka', 'l_agowianka'),
    array('Łeba', 'l_eba'),
    array('Łobżonka', 'l_obz_onka'),
    array('Łomnica', 'l_omnica'),
    array('Łososina', 'l_ososina'),
    array('Łubinka', 'l_ubinka'),
    array('Łupawa', 'l_upawa'),
    array('Łużyca', 'l_uz_yca'),
    array('Łyna', 'l_yna'),
    array('Łęg', 'l_e_g'),
    array('Łękawka', 'l_e_kawka'),
    array('Ścinawa Niemodlińska', 's_cinawa_niemodlin_ska'),
    array('Ścinawka', 's_cinawka'),
    array('Ślina', 's_lina'),
    array('Ślęza', 's_le_za'),
    array('Świder', 's_wider'),
    array('Świślina', 's_wis_lina'),
    array('Żabniczanka', 'z_abniczanka'),
    array('Żylica', 'z_ylica'),
);
