<?php
# URUCHOMIENIE GENEROWANIA W KONSOLI:
#
# php index.php

# TYLKO Z TEJ TABLICY GENEROWANE SĄ SAMPLE
$slownik = array(
    array('tekst do przeczytana ', 'nazwa_pliku_bez_rozszerzenia'),
);







# TA TABLICA TO TYLKO PRZECHOWALNIA
$slownik_wszystkie = array(
    /*
     *
     *
     */
    # rozne
    array('tu eksperymentalna automatyczna stacja pogodowa'),
    array('Stanisław Kłebek 9 adam tadeusz karol', 'sq9atk'),
    array('tu Stanisław Kłebek 9 adam tadeusz karol', 'tu_sq9atk'),
    array('stan pogody z dnia'),
    array('stan pogody z godziny'),
    array('małopolskiego', 'malopolskiego'),
    array('źródło', 'zrodlo'),
    array('komunikat specjalny od'),
    array('komunikat specjalny'),
    array('powtarzam komunikat'),
    array('pamiętaj'),
    array('wróg podsłuchuje'),
    array('las', 'las'),
    array('uwaga','uwaga'),
    array('uwaga uwaga','uwaga_uwaga'),
    array('wróg podsłuchuje','wrog_podsluchuje'),
    /*
     *
     *
     */
    # airly
    array('pył zawieszony Pe eM 1', 'pyl__zawieszony_pm1'),
    array('pył zawieszony Pe eM 10', 'pyl__zawieszony_pm10'),
    array('pył zawieszony Pe eM 2 i pięć dziesiątych', 'pyl__zawieszony_pm25'),
    array('bardzo dobry', 'bardzo_dobry'),
    array('dobry', 'dobry'),
    array('umiarkowany', 'umiarkowany'),
    array('zly', 'zły'),
    array('bardzo zły', 'bardzo_zly'),
    array('stan_ogólny ', 'stan_ogolny'),
    array('airly', 'airly'),
    array('godzina', 'godzina'),
    /*
     *
     *
     */
    # PROPAGACJA
    array('rigreferens', 'rigreference'),
    array('rigreferens kom', 'rigreference_com'),
    array('noaa', 'noaa'),
    array('dzień ', 'dzien'),
    array('noc', 'noc'),
    array('informacje o propagacji', 'informacje_o_propagacji'),
    array('pasma', 'pasma'),
    array('warunki podwyższone', 'warunki_podwyzszone'),
    array('warunki normalne', 'warunki_normalne'),
    array('warunki obniżone', 'warunki_obnizone'),
    array('pasmo zamknięte', 'pasmo_zamkniete'),
    array('160 metrów', '160_metrow'),
    array('80 metrów', '80_metrow'),
    array('40 metrów', '40_metrow'),
    array('20 metrów', '20_metrow'),
    array('10 metrów', '10_metrow'),
    array('6 metrów', '6_metrow'),
    /*
     *
     *
     */
    # OPEN WEATHER MAP
    array('stan z godziny','stan_z_godziny'),
    array('ołpenłeder map', 'open_weather_map'),
    array('burza z lekkimi opadami deszczu'),
    array('burza z opadami deszczu'),
    array('burza z silnymi opadami deszczu'),
    array('niewielka burza'),
    array('burza'),
    array('silna burza'),
    array('przelotna burza'),
    array('burza z lekką mżawką', 'burza_z_lekka_mzawka'),
    array('burza z mżawką', 'burza_z_mzawka'),
    array('burza z silną mżawką', 'burza_z_silna_mzawka'),
    array('lekka mżawka', 'lekka_mzawka'),
    array('mżawka', 'mzawka'),
    array('silna mżawka', 'silna_mzawka'),
    array('lekki mżący deszcz', 'lekki_mzacy_deszcz'),
    array('mżący deszcz', 'mzacy_deszcz'),
    array('silny mżący deszcz', 'silny_mzacy_deszcz'),
    array('ulewa z mżawką', 'ulewa_z_mzawka'),
    array('silna ulewa z mżawką', 'silna_ulewa_z_mzawka'),
    array('ulewa z mżawką', 'ulewa_z_mzawka'),
    array('umiarkowane opady deszczu'),
    array('intensywne opady deszczu'),
    array('bardzo intensywne opady deszczu'),
    array('oberwanie chmury'),
    array('marznący deszcz', 'marznacy_deszcz'),
    array('lekka ulewa'),
    array('ulewa'),
    array('silna ulewa'),
    array('przelotna ulewa'),
    array('niewielkie opady śniegu', 'niewielkie_opady_sniegu'),
    array('opady śniegu', 'opady_sniegu'),
    array('intensywne opady sniegu', 'intensywne_opady_sniegu'),
    array('śnieg z deszczem', 'snieg_z_deszczem'),
    array('śnieg z deszczem', 'snieg_z_deszczem'),
    array('śnieg z niewielkim deszczem', 'snieg_z_niewielkim_deszczem'),
    array('śnieg z deszczem', 'snieg_z_deszczem'),
    array('lekka snieżyca', 'lekka_sniezyca'),
    array('śnieżyca', 'sniezyca'),
    array('intensywna śnieżyca', 'intensywna_sniezyca'),
    array('zamglenia'),
    array('zadymienie'),
    array('mgła', 'mgla'),
    array('kusz i piach', 'kurz_i_piach'),
    array('mgła', 'mgla'),
    array('piasek', 'piasek'),
    array('pył', 'pyl'),
    array('pył wulkaniczny', 'pyl_wulkaniczny'),
    array('szkwały', 'szkwaly'),
    array('tornado'),
    array('bezhmurnie', 'bezchmurnie'),
    array('lekkie zachmurzenie', 'lekkie_zachmurzenie'),
    array('niewielkie zachmurzenie', 'niewielkie_zachmurzenie'),
    array('zachmurzenie umiarkowane', 'zachmurzenie_umiarkowane'),
    array('pochmurno', 'pochmurno'),
    /*
     *
     *
     */
    # promieniowanie
    array('Poziom promieniowania'),
    array('Poziom promieniowania gamma'),
    array('Poziom promieniowania jonizującego'),
    array('Wartość aktualna'),
    array('Średnia wartość dobowa'),
    array('mikrosjiwerta'),
    array('na godzinę'),
    array('setna'),
    array('setne'),
    array('setnych'),
    array('dziesiąta'),
    array('dziesiąte'),
    array('dziesiątych'),
    /*
     *
     *
     */
    # radioactive sq9atk
    array('radioaktiv at hołm org','radioactiveathome_org'),
    array('Poziom promieniowania'),
    array('Poziom promieniowania gamma'),
    array('Poziom promieniowania jonizującego'),
    array('Wartość aktualna'),
    array('Średnia wartość dobowa'),
    array('mikrosjiwerta'),
    array('na godzinę'),
    array('setna'),
    array('setne'),
    array('setnych'),
    array('dziesiąta'),
    array('dziesiąte'),
    array('dziesiątych'),
    /*
     *
     *
     */
    # geomagnetic sq9atk
    array('gis meteo','gis_meteo'),
    array('sytuacja geomagnetyczna w regionie'),
    array('po jutrze'),
    array('krótko po północy'),
    array('nad ranem'),
    array('rano'),
    array('przed południem'),
    array('wczesnym popołudniem'),
    array('po południu'),
    array('wieczorem'),
    array('przed północą'),
    array('brak istotnych zaburzeń geomagnetycznych'),
    array('lekkie zaburzenia geomagnetyczne'),
    array('umiarkowane zabużenia geomagnetyczne'),
    array('mała burza geomagnetyczna'),
    array('umiarkowana burza geomagnetyczna'),
    array('silna burza geomagnetyczna'),
    array('sztorm geomagnetyczny'),
    array('duży sztorm geomagnetyczny'),
    array('niezauważalne'),
    array('znikome'),
    array('lekkie'),
    array('podwyższone'),
    array('umiarkowane'),
    array('duże'),
    array('bardzo duże'),
    array('ekstremalne'),
    array('wahania dobowe'),
    /*
     *
     *
     */
    # Sunrise SQ9ATK
    array('kalendar zoznam eska','calendar_zoznam_sk'),
    array('kalendarium'),
    array('wschód słońca'),
    array('zachód słońca'),
    array('kalendar zoznam sk'),
    /*
     *
     *
     */
    # air pollution SQ9ATK
    array('powietrze małopolska pe el','powietrze_malopolska_pl'),
    array('Informacja o skażeniu powietrza'),
    array('mikrogram'),
    array('mikrogramy'),
    array('mikrogramów'),
    array('na metr sześcienny'),
    array('stacja pomiarowa Kraków'),
    array('stacja pomiarowa Nowy Sącz'),
    array('stacja pomiarowa Tarnów'),
    array('w normie', 'poziom_bardzo_dobry'),
    array('w normie', 'poziom_dobry'),
    array('lekkie skażenie', 'poziom_dostateczny'),
    array('umiarkowane skażenie', 'poziom_umiarkowany'),
    array('wysokie skażenie', 'poziom_zl_y'),
    array('bardzo wysokie skażenie', 'poziom_bardzo_zl_y'),
    array('aleja krasińskiego', 'al_krasin_skiego'),
    array('ulica bulwarowa', 'ul_bulwarowa'),
    array('ulica bujaka', 'ul_bujaka'),
    array('ulica dietla', 'ul_dietla'),
    array('ulica bitwy pod studziankami','ul_bitwy_pod_studziankami'),
    array('ulica franczesko nullo','ul_francesco_nullo'),
    array('ulica handlowa','ul_handlowa'),
    array('ulica księdza romana sitko','ul_ks_romana_sitko'),
    array('ulica nadbrzeżna','ul_nadbrzez_na'),
    array('ulica sienkiewicza','ul_sienkiewicza'),
    array('osiedle Piastów', 'os_piasto_w'),
    array('osiedle ogrody','os_ogrody'),
    array('osiedle związku walki młodych','os_zwia_zku_walki_ml_odych'),
    array('stacja pomiarowa nowy targ','stacja_pomiarowa_nowy_targ'),
    array('stacja pomiarowa olkusz','stacja_pomiarowa_olkusz'),
    array('stacja pomiarowa skawina','stacja_pomiarowa_skawina'),
    array('stacja pomiarowa trzebinia','stacja_pomiarowa_trzebinia'),
    array('stacja pomiarowa zakopane','stacja_pomiarowa_zakopane'),
    array('ulica złoty róg', 'ul_zl_oty_ro_g'),
    array('pył pe em 10', 'pyl__pm10'),
    array('pył pe em 2.5', 'pyl__pm25'),
    array('dwutlenek azotu'),
    array('tlenek węgla'),
    array('dwutlenek siarki'),
    array('ozon'),
    /*
     *
     *
     */
    # daty
    array('pierwszego'),
    array('drugiego'),
    array('trzeciego'),
    array('czwartego'),
    array('piątego', 'piatego'),
    array('szóstego', 'szostego'),
    array('siódmego', 'siodmego'),
    array('ósmego', 'osmego'),
    array('dziewiątego', 'dziewiatego'),
    array('dziesiątego', 'dziesiatego'),
    array('jedenastego'),
    array('dwunastego'),
    array('trzynastego'),
    array('czternastego'),
    array('piętnastego', 'pietnastego'),
    array('szesnastego'),
    array('siedemnastego'),
    array('osiemnastego'),
    array('dziewiętnastego', 'dziewietnastego'),
    array('dwudziestego'),
    array('trzydziestego'),
    /*
     *
     *
     */
    # miesiące
    array('stycznia'),
    array('lutego'),
    array('marca'),
    array('kwietnia'),
    array('maja'),
    array('czerwca'),
    array('lipca'),
    array('sierpnia'),
    array('września', 'wrzesnia'),
    array('października', 'pazdziernika'),
    array('listopada'),
    array('grudnia'),
    /*
     *
     *
     */
    # liczebniki
    array('pierwszy'),
    array('drugi'),
    array('trzeci'),
    array('czwarty'),
    array('piąty', 'piaty'),
    array('piąty najwyższy', 'piaty najwyzszy'),
    array('szósty', 'szosty'),
    array('siódmy', 'siodmy'),
    array('ósmy', 'osmy'),
    array('dziewiąty', 'dziewiaty'),
    array('dziesiąty', 'dziesiaty'),
    /*
     *
     *
     */
    # liczby
    array('zero'),
    array('zero zero'),
    array('jeden'),
    array('dwa'),
    array('trzy'),
    array('cztery'),
    array('pięć', 'piec'),
    array('sześć', 'szesc'),
    array('siedem'),
    array('osiem'),
    array('dziewięć', 'dziewiec'),
    array('dziesięć', 'dziesiec'),
    array('jedenaście', 'jedenascie'),
    array('dwanaście', 'dwanascie'),
    array('trzynaście', 'trzynascie'),
    array('czternaście', 'czternascie'),
    array('piętnaście', 'pietnascie'),
    array('szesnaście', 'szesnascie'),
    array('siedemnaście', 'siedemnascie'),
    array('osiemnaście', 'osiemnascie'),
    array('dziewiętnaście', 'dziewietnascie'),
    array('dwadzieścia', 'dwadziescia'),
    array('trzydzieści', 'trzydziesci'),
    array('czterdzieści', 'czterdziesci'),
    array('pięćdziesiąt', 'piecdziesiat'),
    array('sześćdziesiąt', 'szescdziesiat'),
    array('siedemdziesiąt', 'siedemdziesiat'),
    array('osiemdziesiąt', 'osiemdziesiat'),
    array('dziewięćdziesiąt', 'dziewiecdziesiat'),
    array('sto'),
    array('dwieście', 'dwiescie'),
    array('trzysta', ''),
    array('czterysta'),
    array('pięćset', 'piecset'),
    array('sześćset', 'szescset'),
    array('siedemset'),
    array('osiemset'),
    array('dziewięćset', 'dziewiecset'),
    array('tysiąc', 'tysiac'),
    array('tysiące', 'tysiace'),
    array('tysięcy', 'tysiecy'),
    array('tysiące','tysia_ce'),
    array('zero zero','zero-zero'),
    /*
     *
     *
     */
    # godziny
    array('pierwsza'),
    array('druga'),
    array('trzecia'),
    array('czwarta'),
    array('piąta', 'piata'),
    array('szósta', 'szosta'),
    array('siódma', 'siodma'),
    array('ósma', 'osma'),
    array('dziewiąta', 'dziewiata'),
    array('dziesiąta', 'dziesiata'),
    array('jedenasta'),
    array('dwunasta'),
    array('trzynasta'),
    array('czternasta'),
    array('piętnasta', 'pietnasta'),
    array('szesnasta'),
    array('siedemnasta'),
    array('osiemnasta'),
    array('dziewiętnasta', 'dziewietnasta'),
    array('dwudziesta'),
    /*
     *
     *
     */
    # nazwy zjawisk pogodowych (dla Yahoo! Weather)
    array('bezchmurnie'),
    array('burza'),
    array('burza tropikalna'),
    array('deszcz'),
    array('deszcz i deszcz ze śniegiem', 'deszcz i deszcz ze sniegiem'),
    array('deszcz i grad'),
    array('deszcz ze śniegiem', 'deszcz ze sniegiem'),
    array('grad'),
    array('huragan'),
    array('marznący deszcz', 'marznacy deszcz'),
    array('pochmurno'),
    array('przelotne opady'),
    array('przelotne opady śniegu', 'przelotne opady sniegu'),
    array('przymrozki'),
    array('pył', 'pyl'),
    array('silne burze'),
    array('silny wiatr'),
    array('słabe zachmurzenie', 'slabe zachmurzenie'),
    array('słaby śnieg', 'slaby snieg'),
    array('smog'),
    array('śnieg', 'snieg'),
    array('śnieg i deszcz ze śniegiem', 'snieg i deszcz ze sniegiem'),
    array('tornado'),
    array('wietrznie'),
    array('zamglenia'),
    array('zawieje śnieżne', 'zawieje sniezne'),
    array('jahu łeder', 'y_weather'),
    /*
     *
     *
     */
    # różne
    array('temperatura'),
    array('stopień celsjusza', 'stopien celsjusza'),
    array('minus'),
    array('stopnie celsjusza'),
    array('stopni celsjusza'),
    array('kierunek wiatru'),
    array('północny', 'polnocny'),
    array('północno', 'polnocno'),
    array('wschodni', 'wschodni'),
    array('wschodnio'),
    array('zachodni'),
    array('zachodnio'),
    array('południowy', 'poludniowy'),
    array('południowo', 'poludniowo'),
    array('wilgotność', 'wilgotnosc'),
    array('procent'),
    array('prędkość wiatru', 'predkosc wiatru'),
    array('stopień', 'stopien'),
    array('stopnie'),
    array('stopni'),
    array('widoczność', 'widocznosc'),
    array('kilometr'),
    array('kilometry'),
    array('kilometrów', 'kilometrow'),
    array('prognoza na następne', 'prognoza na nastepne'),
    array('godzin'), array('godzina'),
    array('godziny'),
    array('z godziny'),
    array('temperatura od'),
    array('metr na sekundę', 'metr na sekunde'),
    array('metry na sekundę', 'metry na sekunde'),
    array('metrów na sekunde', 'metrow na sekunde'),
    array('kilometr na godzinę', 'kilometr na godzine'),
    array('kilometry na godzinę', 'kilometry na godzine'),
    array('kilometrów na godzinę', 'kilometrow na godzine'),
    array('ciśnienie', 'cisnienie'),
    array('hektopaskal'),
    array('hektopaskale'),
    array('hektopaskali'),
    array('tendencja spadkowa'),
    array('tendencja wzrostowa'),
    array('temperatura odczuwalna'),
    array('temperatura minimalna'),
    array('maksymalna'),
    array('następnie', 'nastepnie'),
    array('obowiązuje', 'obowiazuje'),
    /*
     *
     *
     */
    # literowanie
    array('adam', 'a'),
    array('barbara', 'b'),
    array('celina', 'c'),
    array('dorota', 'd'),
    array('edward', 'e'),
    array('franciszek', 'f'),
    array('grażyna', 'g'),
    array('halina', 'h'),
    array('irena', 'i'),
    array('jadwiga', 'j'),
    array('karol', 'k'),
    array('ludwik', 'l'),
    array('maria', 'm'),
    array('natalia', 'n'),
    array('olga', 'o'),
    array('paweł', 'p'),
    array('kłebek', 'q'), # wł. Quebec
    array('roman', 'r'),
    array('stefan', 's'),
    array('tadeusz', 't'),
    array('urszula', 'u'),
    array('violetta', 'v'),
    array('wacław', 'w'),
    array('xawery', 'x'),
    array('ypsylon', 'y'), # wł. Ypsilon
    array('zygmunt', 'z'),
    array('łamane'),
    /*
     *
     *
     */
    # Sample potrzebne dla modułu meteoalarm (cała Polska)
    array('lombardia','lombardia'),
    array('zagrożenia meteorologiczne dla województwa', 'zagrozenia_meteorologiczne_dla_wojewodztwa'),
    array('lombardia','lombardia'),
    array('mazowieckiego'),
    array('lubuskiego'),
    array('zachodniopomorskiego'),
    array('pomorskiego'),
    array('dolnośląskiego', 'dolnoslaskiego'),
    array('opolskiego'),
    array('śląskiego', 'slaskiego'),
    array('małopolskiego'),
    array('podkarpackiego'),
    array('świętokrzyskiego', 'swietokrzyskiego'),
    array('łódzkiego', 'lodzkiego'),
    array('wielkopolskiego'),
    array('kujawsko-pomorskiego'),
    array('warminsko-mazurskiego'),
    array('lubelskiego'),
    array('podlaskiego'),
    array('dziś', 'dzis'),
    array('jutro'),
    array('śnieg lub oblodzenie', 'snieg lub oblodzenie'),
    array('burze'),
    array('mgły', 'mgly'),
    array('niskie temperatury'),
    array('wysokie temperatury'),
    array('zjawiska strefy brzegowej'),
    array('pożary lasów', 'pozary lasow'),
    array('lawiny'),
    array('intensywne opady deszczu'),
    array('inne zagrożenia', 'inne zagrozenia'),
    array('poziom zagrożenia', 'poziom zagrozenia'),
    array('nieokreślony', 'nieokreslony'),
    array('niski'),
    array('średni', 'sredni'),
    array('wysoki'),
    array('burza śnieżna', 'burza sniezna'),
    array('częściowe zachmurzenie', 'czesciowe zachmurzenie'),
    array('zachmurzenie załkowite', 'zachmurzenie calkowite'),
    array('grad'),
    array('intensywne opady śniegu', 'intensywne opady sniegu'),
    array('lokalna przelotna marznąca mżawka', 'lokalna przelotna marznaca mzawka'),
    array('lokalne burze'),
    array('lokalne przelotne opady deszczu'),
    array('lokalny słaby deszcz', 'lokalny slaby deszcz'),
    array('marznąca mgła', 'marznaca mgla'),
    array('marznąca mżawka', 'marznaca mzawka'),
    array('mgła', 'mgla'),
    array('mżawka', 'mzawka'),
    array('opady śniegu', 'opady sniegu'),
    array('pochmurno'),
    array('przelotne opady deszczu'),
    array('przelotne ulewy'),
    array('słabe opady marznącego deszczu', 'slabe opady marznacego deszczu'),
    array('słabe opady śniegu', 'slabe opady sniegu'),
    array('słabe opady śniegu z deszczem', 'slabe opady sniegu z deszczem'),
    array('słabe opady śniegu ziarnistego', 'slabe opady sniegu ziarnistego'),
    array('słabe przelotne opady deszczu', 'slabe przelotne opady deszczu'),
    array('słaby deszcz', 'slaby deszcz'),
    array('śnieg', 'snieg'),
    array('śnieg z deszczem', 'snieg z deszczem'),
    array('ulewny deszcz'),
    array('ulewy'),
    array('umiarkowane lub ciężkie opady śniegu z deszczem', 'umiarkowane lub ciezkie opady sniegu z deszczem'),
    array('umiarkowane opady deszczu', ''),
    array('umiarkowane opady marznącego deszczu', 'umiarkowane opady marznacego deszczu'),
    array('umiarkowane opady śniegu', 'umiarkowane opady sniegu'),
    array('umiarkowane opady śniegu z deszczem', 'umiarkowane opady sniegu z deszczem'),
    array('umiarkowane opady śniegu ziarnistego', 'umiarkowane opady sniegu ziarnistego'),
    array('zachmurzenie całkowite', 'zachmurzenie calkowite'),
    array('zamglenia'),
    array('zamieć śnieżna', 'zamiec sniezna'),
    array('pokrywa chmur'),
    array('łorld łeder onlajn', 'worldweatheronline'),
    array('stopien zagrozenia lawinowego'),
        /*
     *
     *
     */
    # Sample dla wodowskazów
    array('rzeka'),
    array('wodowskaz'),
    array('stopień czuwania', 'stopien_czuwania'),
    array('stopień gotowości', 'stopien_gotowosci'),
    array('stopień zagrożenia', 'stopien_zagrozenia'),
    array('stopień ekstremalnych powodzi', 'stopien_ekstremalnych_powodzi'),
    array('iemgiewu', 'imgw'),
    array('komunikat hydrologiczny iemgiewu', 'komunikat_hydrologiczny_imgw'),
    array('meteoalarm eu'),
    array('lokalny komunikat hydrologiczny'),
    array('komunikat hydrologiczny'),
    array('przekroczenia stanów ostrzegawczych', 'przekroczenia stanow alarmowych'),
    array('przekroczenia stanów alarmowych', 'przekroczenia stanow ostrzegawczych'),
    array('promieniowanie tła'),
    array('przecinek', 'przecinek'),
    array('mikrosjiwerta na godzinę', 'mikrosiwerta_na_godzine'),
    array('w normie'),
    array('podwyższone'),
    array('wysokie'),
    /*
     *
     *
     */
    # rzeki
    array('biała nida','biała_nida'),
    array('cicha woda','cicha_woda'),
    array('czarna przemsza','czarna_przemsza'),
    array('czarna staszowska','czarna_staszowska'),
    array('czarna wisełka','czarna_wisel_ka'),
    array('gostynka','gostynka'),
    array('grabinianka','grabinianka'),
    array('gromiec','gromiec'),
    array('iłowica','il_owica'),
    array('łagowica','l_agowica'),
    array('potok kościeliski','potok_kos_cieliski'),
    array('wielopolka','wielopolka'),
    array('trybsz','trybsz'),
    array('Barycz', 'barycz'),
    array('Bauda', 'bauda'),
    array('Bawół', 'bawo_l_'),
    array('Bałtyk', 'bal_tyk'),
    array('Biała', 'bial_a'),
    array('Biała Głuchołaska', 'bial_a_gl_uchol_aska'),
    array('Biała Lądecka', 'bial_a_la_decka'),
    array('Biała Przemsza', 'bial_a_przemsza'),
    array('Biała Wisełka', 'bial_a_wisel_ka'),
    array('Białka', 'bial_ka'),
    array('Biały Dunajec', 'bial_y_dunajec'),
    array('Biebrza', 'biebrza'),
    array('Bielawa', 'bielawa'),
    array('Bierawka', 'bierawka'),
    array('Bobrza', 'bobrza'),
    array('Boczne Koryto Opawy', 'boczne_koryto_opawy'),
    array('Bogacica', 'bogacica'),
    array('Brda', 'brda'),
    array('Brennica', 'brennica'),
    array('Breń', 'bren_'),
    array('Brynica', 'brynica'),
    array('Brzeźnica', 'brzez_nica'),
    array('Brzozówka', 'brzozo_wka'),
    array('Budkowiczanka', 'budkowiczanka'),
    array('Budzówka', 'budzo_wka'),
    array('Bug', 'bug'),
    array('Bukowa', 'bukowa'),
    array('Bystra', 'bystra'),
    array('Bystrzyca', 'bystrzyca'),
    array('Bystrzyca Dusznicka', 'bystrzyca_dusznicka'),
    array('Bzura', 'bzura'),
    array('Bóbr', 'bo_br'),
    array('Cieśnina Dziwna', 'cies_nina_dziwna'),
    array('Czarna', 'czarna'),
    array('Czarna Nida', 'czarna_nida'),
    array('Czarna Woda', 'czarna_woda'),
    array('Czarny Dunajec', 'czarny_dunajec'),
    array('Czarny Potok', 'czarny_potok'),
    array('Czerna Mała', 'czerna_mal_a'),
    array('Czerna Wielka', 'czerna_wielka'),
    array('Czerwona Woda', 'czerwona_woda'),
    array('Drama', 'drama'),
    array('Drawa', 'drawa'),
    array('Drwęca', 'drwe_ca'),
    array('Drwęca Warmińska', 'drwe_ca_warmin_ska'),
    array('Drzewiczka', 'drzewiczka'),
    array('Dunajec', 'dunajec'),
    array('Elbląg', 'elbla_g'),
    array('Ełk', 'el_k'),
    array('Gostynia', 'gostynia'),
    array('Gołdapa', 'gol_dapa'),
    array('Grabia', 'grabia'),
    array('Grabinka', 'grabinka'),
    array('Guber', 'guber'),
    array('Gwda', 'gwda'),
    array('Hoczewka', 'hoczewka'),
    array('Huczwa', 'huczwa'),
    array('Ina', 'ina'),
    array('Iłownica', 'il_ownica'),
    array('Iłżanka', 'il_z_anka'),
    array('Jasiołka', 'jasiol_ka'),
    array('Jedlica', 'jedlica'),
    array('Jegrznia', 'jegrznia'),
    array('Jezioro Druzno', 'jez._druzno'),
    array('Jezioro Drwęckie', 'jez._drwe_ckie'),
    array('Jezioro Ełckie', 'jez._el_ckie'),
    array('Jezioro Mamry', 'jez._mamry'),
    array('Jezioro Raduńskie Górne', 'jez._radun_skie_go_rne'),
    array('Jezioro Rajgrodzkie', 'jez._rajgrodzkie'),
    array('Jezioro Roś', 'jez._ros_'),
    array('Jezioro Wadąg', 'jez._wada_g'),
    array('Jezioro Łebsko', 'jez._l_ebsko'),
    array('Jeziorka', 'jeziorka'),
    array('Kaczawa', 'kaczawa'),
    array('Kamienica', 'kamienica'),
    array('Kamienna', 'kamienna'),
    array('Kanał Mosiński', 'kanal__mosin_ski'),
    array('Kanał Raduński', 'kanal__radun_ski'),
    array('Kanał Ślesiński', 'kanal__s_lesin_ski'),
    array('Kiełbaska', 'kiel_baska'),
    array('Kirowa Woda', 'kirowa_woda'),
    array('Klikawa', 'klikawa'),
    array('Koprzywianka', 'koprzywianka'),
    array('Koszarawa', 'koszarawa'),
    array('Krzczonówka', 'krzczono_wka'),
    array('Krzna', 'krzna'),
    array('Kuroch', 'kuroch'),
    array('Kwisa', 'kwisa'),
    array('Kłodnica', 'kl_odnica'),
    array('Lepietnica', 'lepietnica'),
    array('Liswarta', 'liswarta'),
    array('Liwa', 'liwa'),
    array('Liwiec', 'liwiec'),
    array('Lubaczówka', 'lubaczo_wka'),
    array('Lubieńka', 'lubien_ka'),
    array('Lubsza', 'lubsza'),
    array('Luciąża', 'lucia_z_a'),
    array('Martwa Wisła', 'martwa_wisl_a'),
    array('Mała Panew', 'mal_a_panew'),
    array('Miedzianka', 'miedzianka'),
    array('Mierzawa', 'mierzawa'),
    array('Mitręga', 'mitre_ga'),
    array('Mleczka', 'mleczka'),
    array('Morwawa', 'morwawa'),
    array('Motława', 'motl_awa'),
    array('Mroga', 'mroga'),
    array('Mszanka', 'mszanka'),
    array('Mławka', 'ml_awka'),
    array('Młynówka', 'ml_yno_wka'),
    array('Narew', 'narew'),
    array('Narewka', 'narewka'),
    array('Ner', 'ner'),
    array('Nereśl', 'neres_l'),
    array('Netta', 'netta'),
    array('Nida', 'nida'),
    array('Nieciecz', 'nieciecz'),
    array('Niedziczanka', 'niedziczanka'),
    array('Niesób', 'nieso_b'),
    array('Nogat', 'nogat'),
    array('Noteć', 'notec_'),
    array('Nurzec', 'nurzec'),
    array('Nysa Kłodzka', 'nysa_kl_odzka'),
    array('Nysa Szalona', 'nysa_szalona'),
    array('Nysa Łużycka', 'nysa_l_uz_ycka'),
    array('Obra', 'obra'),
    array('Ochotnica', 'ochotnica'),
    array('Odra', 'odra'),
    array('Oleśnica', 'oles_nica'),
    array('Olza', 'olza'),
    array('Omulew', 'omulew'),
    array('Opawa', 'opawa'),
    array('Orla', 'orla'),
    array('Orlanka', 'orlanka'),
    array('Orz', 'orz'),
    array('Orzyc', 'orzyc'),
    array('Osa', 'osa'),
    array('Osobłoga', 'osobl_oga'),
    array('Osława', 'osl_awa'),
    array('Oława', 'ol_awa'),
    array('Ołobok', 'ol_obok'),
    array('Parsęta', 'parse_ta'),
    array('Pasłęka', 'pasl_e_ka'),
    array('Pełcznica', 'pel_cznica'),
    array('Pielnica', 'pielnica'),
    array('Pilica', 'pilica'),
    array('Pisa', 'pisa'),
    array('Piława', 'pil_awa'),
    array('Podgórna', 'podgo_rna'),
    array('Pokrzywianka', 'pokrzywianka'),
    array('Polska Woda', 'polska_woda'),
    array('Polski Rów', 'polski_ro_w'),
    array('Poprad', 'poprad'),
    array('Poroniec', 'poroniec'),
    array('Powa', 'powa'),
    array('Prosna', 'prosna'),
    array('Prudnik', 'prudnik'),
    array('Przemsza', 'przemsza'),
    array('Prądnik', 'pra_dnik'),
    array('Psina', 'psina'),
    array('Pszczynka', 'pszczynka'),
    array('Pór', 'po_r'),
    array('Raba', 'raba'),
    array('Radew', 'radew'),
    array('Radomka', 'radomka'),
    array('Radunia', 'radunia'),
    array('Rawka', 'rawka'),
    array('Reda', 'reda'),
    array('Rega', 'rega'),
    array('Rgilewka', 'rgilewka'),
    array('Ropa', 'ropa'),
    array('Rozoga', 'rozoga'),
    array('Ruda', 'ruda'),
    array('Rudawa', 'rudawa'),
    array('Ruż', 'ruz_'),
    array('San', 'san'),
    array('Sidra', 'sidra'),
    array('Skawa', 'skawa'),
    array('Skawica', 'skawica'),
    array('Skawinka', 'skawinka'),
    array('Skora', 'skora'),
    array('Skroda', 'skroda'),
    array('Sokołda', 'sokol_da'),
    array('Solinka', 'solinka'),
    array('Soła', 'sol_a'),
    array('Sośniak', 'sos_niak'),
    array('Stobnica', 'stobnica'),
    array('Stobrawa', 'stobrawa'),
    array('Stradomka', 'stradomka'),
    array('Stradunia', 'stradunia'),
    array('Stryszawka', 'stryszawka'),
    array('Strzegomka', 'strzegomka'),
    array('Supraśl', 'supras_l'),
    array('Swędrnia', 'swe_drnia'),
    array('Szkarpawa', 'szkarpawa'),
    array('Szkwa', 'szkwa'),
    array('Szkło', 'szkl_o'),
    array('Szprotawa', 'szprotawa'),
    array('Szreniawa', 'szreniawa'),
    array('Sąsiecznica', 'sa_siecznica'),
    array('Słupia', 'sl_upia'),
    array('Tanew', 'tanew'),
    array('Trzebośnica', 'trzebos_nica'),
    array('Tuja', 'tuja'),
    array('Tyśmienica', 'tys_mienica'),
    array('Uszwica', 'uszwica'),
    array('Utrata', 'utrata'),
    array('Wapienica', 'wapienica'),
    array('Warta', 'warta'),
    array('Wałsza', 'wal_sza'),
    array('Wda', 'wda'),
    array('Wel', 'wel'),
    array('Wetlina', 'wetlina'),
    array('Wełna', 'wel_na'),
    array('Wiar', 'wiar'),
    array('Widawa', 'widawa'),
    array('Widawka', 'widawka'),
    array('Wielki Rogoźnik', 'wielki_rogoz_nik'),
    array('Wieprz', 'wieprz'),
    array('Wieprza', 'wieprza'),
    array('Wieprzówka', 'wieprzo_wka'),
    array('Wierna Rzeka', 'wierna_rzeka'),
    array('Wierzyca', 'wierzyca'),
    array('Wilczka', 'wilczka'),
    array('Wissa', 'wissa'),
    array('Wisznia', 'wisznia'),
    array('Wisła', 'wisl_a'),
    array('Wisłok', 'wisl_ok'),
    array('Wisłoka', 'wisl_oka'),
    array('Witka', 'witka'),
    array('Wkra', 'wkra'),
    array('Woda Ujsolska', 'woda_ujsolska'),
    array('Wołosaty', 'wol_osaty'),
    array('Wrześnica', 'wrzes_nica'),
    array('Wąska', 'wa_ska'),
    array('Węgorapa', 'we_gorapa'),
    array('Zalew Szczeciński', 'zalew_szczecin_ski'),
    array('Zalew Wiślany', 'zalew_wis_lany'),
    array('Złoty Potok', 'zl_oty_potok'),
    array('Łada', 'l_ada'),
    array('Łagowianka', 'l_agowianka'),
    array('Łeba', 'l_eba'),
    array('Łobżonka', 'l_obz_onka'),
    array('Łomnica', 'l_omnica'),
    array('Łososina', 'l_ososina'),
    array('Łubinka', 'l_ubinka'),
    array('Łupawa', 'l_upawa'),
    array('Łużyca', 'l_uz_yca'),
    array('Łyna', 'l_yna'),
    array('Łęg', 'l_e_g'),
    array('Łękawka', 'l_e_kawka'),
    array('Ścinawa Niemodlińska', 's_cinawa_niemodlin_ska'),
    array('Ścinawka', 's_cinawka'),
    array('Ślina', 's_lina'),
    array('Ślęza', 's_le_za'),
    array('Świder', 's_wider'),
    array('Świślina', 's_wis_lina'),
    array('Żabniczanka', 'z_abniczanka'),
    array('Żylica', 'z_ylica'),
    /*
     *
     *
     */
    #   wodowskazy
    array('czaniec kobiernice', 'czaniec_kobiernice'),
    array('kraków','krakow'),
    array('kraków','krako_w'),
    array('kraków bielany','krako_wb_ielany'),
    array('mielec','mielec'),
    array('nowy bieruń','nowy_bierun_'),
    array('nowy sącz','nowy_sa_cz'),
    array('okocim','okocim'),
    array('okocim el es pe o','okocim_lspo'),
    array('czaniec kobiernice','czaniec_(kobiernice)'),
    array('borki mizerów','borki_mizerów'),
    array('lipnica murowana','lipnica_murowana'),
    array('rabka','rabka'),
    array('muszyna','muszyna'),

    array('Annopol', 'annopol'),
    array('Babino', 'babino'),
    array('Balice', 'balice'),
    array('Banie Mazurskie', 'banie_mazurskie'),
    array('Barcinek', 'barcinek'),
    array('Bardo', 'bardo'),
    array('Bardy', 'bardy'),
    array('Bągart', 'ba_gart'),
    array('Biała Góra', 'bial_a_go_ra'),
    array('Biała Nyska', 'bial_a_nyska'),
    array('Białobrzeg Bliższy', 'bial_obrzeg_bliz_szy'),
    array('Białobrzegi', 'bial_obrzegi'),
    array('Białobrzezie', 'bial_obrzezie'),
    array('Białogard', 'bial_ogard'),
    array('Białogórzyno', 'bial_ogo_rzyno'),
    array('Białośliwie', 'bial_os_liwie'),
    array('Białowieża - Park', 'bial_owiez_a___park'),
    array('Bielawy', 'bielawy'),
    array('Bielinek', 'bielinek'),
    array('Bieruń Nowy', 'bierun__nowy'),
    array('Biłgoraj', 'bil_goraj'),
    array('Biskupice', 'biskupice'),
    array('Bledzew', 'bledzew'),
    array('Błażkowa', 'bl_az_kowa'),
    array('Bobry', 'bobry'),
    array('Bocheniec', 'bocheniec'),
    array('Bogatynia', 'bogatynia'),
    array('Bogdaj', 'bogdaj'),
    array('Bogdaszowice', 'bogdaszowice'),
    array('Bogusław', 'bogusl_aw'),
    array('Bojanów', 'bojano_w'),
    array('Bojszowy', 'bojszowy'),
    array('Bondary', 'bondary'),
    array('Borkowo', 'borkowo'),
    array('Bornity', 'bornity'),
    array('Borów', 'boro_w'),
    array('Borucino', 'borucino'),
    array('Borzęcin', 'borze_cin'),
    array('Bożepole Szlacheckie', 'boz_epole_szlacheckie'),
    array('Branice', 'branice'),
    array('Braniewo', 'braniewo'),
    array('Brańsk', 'bran_sk'),
    array('Brodnica', 'brodnica'),
    array('Brody Iłżeckie', 'brody_il_z_eckie'),
    array('Brody Pomorskie', 'brody_pomorskie'),
    array('Brynica', 'brynica'),
    array('Brzeg', 'brzeg'),
    array('Brzeg Dolny', 'brzeg_dolny'),
    array('Brzegi', 'brzegi'),
    array('Brzesko-Miasto (Lsop)', 'brzesko_miasto_lsop'),
    array('Brzeźnica', 'brzez_nica'),
    array('Bukowna', 'bukowna'),
    array('Bukówka', 'buko_wka'),
    array('Burzenin', 'burzenin'),
    array('Burzyn', 'burzyn'),
    array('Bystrzyca Kłodzka', 'bystrzyca_kl_odzka'),
    array('Bzin', 'bzin'),
    array('Chałupki', 'chal_upki'),
    array('Charnowo', 'charnowo'),
    array('Charytany', 'charytany'),
    array('Chełmno', 'chel_mno'),
    array('Chojnów', 'chojno_w'),
    array('Chraboły', 'chrabol_y'),
    array('Chwaliszów', 'chwaliszo_w'),
    array('Cieszyn', 'cieszyn'),
    array('Cięcina', 'cie_cina'),
    array('Ciężkowice', 'cie_z_kowice'),
    array('Cigacice', 'cigacice'),
    array('Cisna', 'cisna'),
    array('Czachy', 'czachy'),
    array('Czaniec-Kobiernice', 'czaniec_kobiernice'),
    array('Czarna Woda', 'czarna_woda'),
    array('Czarnków', 'czarnko_w'),
    array('Czarnowo', 'czarnowo'),
    array('Czchów', 'czcho_w'),
    array('Czechowice-Bestwina', 'czechowice_bestwina'),
    array('Czechowice-Dziedzice', 'czechowice_dziedzice'),
    array('Czekarzewice', 'czekarzewice'),
    array('Czernichów-Prom', 'czernicho_w_prom'),
    array('Daleszyce', 'daleszyce'),
    array('Darłowo', 'darl_owo'),
    array('Dąbie', 'da_bie'),
    array('Dąbrowa', 'da_browa'),
    array('Dąbrowa Bolesławiecka', 'da_browa_bolesl_awiecka'),
    array('Dębe', 'de_be'),
    array('Dęblin', 'de_blin'),
    array('Dębowo', 'de_bowo'),
    array('Dobczyce', 'dobczyce'),
    array('Dobra', 'dobra'),
    array('Dobroszów Wielki', 'dobroszo_w_wielki'),
    array('Dobrylas', 'dobrylas'),
    array('Dolna Kępa (Nowotki)', 'dolna_ke_pa_nowotki'),
    array('Domaradz', 'domaradz'),
    array('Dorohusk', 'dorohusk'),
    array('Drawiny', 'drawiny'),
    array('Drogomyśl', 'drogomys_l'),
    array('Dunino', 'dunino'),
    array('Dwernik', 'dwernik'),
    array('Dynów', 'dyno_w'),
    array('Działoszyn', 'dzial_oszyn'),
    array('Dzierżoniów', 'dzierz_onio_w'),
    array('Dziwnów', 'dziwno_w'),
    array('Elbląg', 'elbla_g'),
    array('Elgiszewo', 'elgiszewo'),
    array('Ełk ', 'el_k_'),
    array('Fasty', 'fasty'),
    array('Fordon', 'fordon'),
    array('Frankopol', 'frankopol'),
    array('Gdańsk Port Północny', 'gdan_sk_port_po_l_nocny'),
    array('Gdańsk Przegalina', 'gdan_sk_przegalina'),
    array('Gdańsk Sobieszewo', 'gdan_sk_sobieszewo'),
    array('Gdańsk Świbno', 'gdan_sk_s_wibno'),
    array('Gdańsk Ujście Wisły', 'gdan_sk_ujs_cie_wisl_y'),
    array('Gdańska Głowa (Drewnica)', 'gdan_ska_gl_owa_drewnica'),
    array('Gdynia', 'gdynia'),
    array('Giżycko', 'giz_ycko'),
    array('Gliwice', 'gliwice'),
    array('Gliwice-Łabędy', 'gliwice_l_abe_dy'),
    array('Głogów', 'gl_ogo_w'),
    array('Głowaczowa', 'gl_owaczowa'),
    array('Głuchołazy', 'gl_uchol_azy'),
    array('Gniechowice', 'gniechowice'),
    array('Goczałkowice', 'goczal_kowice'),
    array('Godowa', 'godowa'),
    array('Goleniów', 'golenio_w'),
    array('Gołdap 2', 'gol_dap_2'),
    array('Gołkowice', 'gol_kowice'),
    array('Goręczyno', 'gore_czyno'),
    array('Gorliczyna', 'gorliczyna'),
    array('Gorzów Śląski', 'gorzo_w_s_la_ski'),
    array('Gorzów Wielkopolski', 'gorzo_w_wielkopolski'),
    array('Gorzuchów', 'gorzucho_w'),
    array('Gościmiec', 'gos_cimiec'),
    array('Gozdowice', 'gozdowice'),
    array('Gozdów', 'gozdo_w'),
    array('Górki Wielkie', 'go_rki_wielkie'),
    array('Grabno', 'grabno'),
    array('Grabówka', 'grabo_wka'),
    array('Grębów', 'gre_bo_w'),
    array('Grudziądz', 'grudzia_dz'),
    array('Grybów', 'grybo_w'),
    array('Gryfino', 'gryfino'),
    array('Gryfów Śląski', 'gryfo_w_s_la_ski'),
    array('Grzegorzew', 'grzegorzew'),
    array('Gubin', 'gubin'),
    array('Gusin', 'gusin'),
    array('Harasimowicze', 'harasimowicze'),
    array('Harasiuki', 'harasiuki'),
    array('Hel', 'hel'),
    array('Hoczew', 'hoczew'),
    array('Iłowa', 'il_owa'),
    array('Iskrzynia', 'iskrzynia'),
    array('Istebna', 'istebna'),
    array('Izbica', 'izbica'),
    array('Jakubkowice', 'jakubkowice'),
    array('Jakuszyce', 'jakuszyce'),
    array('Januszewice', 'januszewice'),
    array('Jarnołtów', 'jarnol_to_w'),
    array('Jarnołtówek', 'jarnol_to_wek'),
    array('Jarosław', 'jarosl_aw'),
    array('Jasło', 'jasl_o'),
    array('Jawiszowice', 'jawiszowice'),
    array('Jawor', 'jawor'),
    array('Jelenia Góra', 'jelenia_go_ra'),
    array('Jeleń', 'jelen_'),
    array('Jordanów', 'jordano_w'),
    array('Jugowice', 'jugowice'),
    array('Jurkiszki', 'jurkiszki'),
    array('Kalisty', 'kalisty'),
    array('Kalnica', 'kalnica'),
    array('Kamesznica', 'kamesznica'),
    array('Kamieniec Ząbkowicki', 'kamieniec_za_bkowicki'),
    array('Kamienna Góra', 'kamienna_go_ra'),
    array('Kamionka', 'kamionka'),
    array('Kanclerzowice', 'kanclerzowice'),
    array('Karłowice', 'karl_owice'),
    array('Karpowicze', 'karpowicze'),
    array('Karsy', 'karsy'),
    array('Kasinka Mała', 'kasinka_mal_a'),
    array('Kazanów', 'kazano_w'),
    array('Kępa Polska', 'ke_pa_polska'),
    array('Kęszyce', 'ke_szyce'),
    array('Klęczany', 'kle_czany'),
    array('Kłodzko', 'kl_odzko'),
    array('Kłudzice', 'kl_udzice'),
    array('Koło', 'kol_o'),
    array('Kołobrzeg', 'kol_obrzeg'),
    array('Konin-Morzysław', 'konin_morzysl_aw'),
    array('Koniówka', 'konio_wka'),
    array('Kopice', 'kopice'),
    array('Koprzywnica', 'koprzywnica'),
    array('Korzeńsko', 'korzen_sko'),
    array('Korzybie', 'korzybie'),
    array('Kostrzyn Nad Odrą', 'kostrzyn_nad_odra_'),
    array('Koszyce Wielkie', 'koszyce_wielkie'),
    array('Kościan', 'kos_cian'),
    array('Kościelec', 'kos_cielec'),
    array('Kościelisko-Kiry', 'kos_cielisko_kiry'),
    array('Kośmin', 'kos_min'),
    array('Kowanówko', 'kowano_wko'),
    array('Kowary', 'kowary'),
    array('Kozłowa Góra', 'kozl_owa_go_ra'),
    array('Koźle', 'koz_le'),
    array('Krajowice', 'krajowice'),
    array('Kraków-Bielany', 'krako_w_bielany'),
    array('Krapkowice', 'krapkowice'),
    array('Krasków', 'krasko_w'),
    array('Krasnystaw', 'krasnystaw'),
    array('Kraszewice', 'kraszewice'),
    array('Krąplewice', 'kra_plewice'),
    array('Krempna-Kotań', 'krempna_kotan_'),
    array('Kręciwilk', 'kre_ciwilk'),
    array('Krosno', 'krosno'),
    array('Krościenko', 'kros_cienko'),
    array('Krówniki', 'kro_wniki'),
    array('Krubice', 'krubice'),
    array('Krupski Młyn', 'krupski_ml_yn'),
    array('Kryłów', 'kryl_o_w'),
    array('Krzczonów', 'krzczono_w'),
    array('Krzyczew', 'krzyczew'),
    array('Krzywa Góra', 'krzywa_go_ra'),
    array('Krzyż', 'krzyz_'),
    array('Krzyżanowice', 'krzyz_anowice'),
    array('Kudowa-Zdrój-Zakrze', 'kudowa_zdro_j_zakrze'),
    array('Kule', 'kule'),
    array('Kulesze Chobotki', 'kulesze_chobotki'),
    array('Kuligi', 'kuligi'),
    array('Kunów', 'kuno_w'),
    array('Kuźnica Skakawska', 'kuz_nica_skakawska'),
    array('Kuźnica Sulikowska', 'kuz_nica_sulikowska'),
    array('Kwiatkówek', 'kwiatko_wek'),
    array('Kwidzyn', 'kwidzyn'),
    array('Las', 'las'),
    array('Ląd', 'la_d'),
    array('Lądek-Zdrój', 'la_dek_zdro_j'),
    array('Lenartowice', 'lenartowice'),
    array('Lesko', 'lesko'),
    array('Leśna', 'les_na'),
    array('Leżachów', 'lez_acho_w'),
    array('Lębork 2', 'le_bork_2'),
    array('Lgota Nadwarcie', 'lgota_nadwarcie'),
    array('Lidzbark', 'lidzbark'),
    array('Lipnica Murowana (Lsop)', 'lipnica_murowana_lsop'),
    array('Lubachów', 'lubacho_w'),
    array('Lubartów', 'lubarto_w'),
    array('Lubień', 'lubien_'),
    array('Ludźmierz', 'ludz_mierz'),
    array('Lutomiersk', 'lutomiersk'),
    array('Łabowa', 'l_abowa'),
    array('Łabuzie', 'l_abuzie'),
    array('Łagisza', 'l_agisza'),
    array('Łapanów-Rynek (Lsop)', 'l_apano_w_rynek_lsop'),
    array('Łask', 'l_ask'),
    array('Łaziska', 'l_aziska'),
    array('Łażany', 'l_az_any'),
    array('Łąki', 'l_a_ki'),
    array('Łeba', 'l_eba'),
    array('Łękawica', 'l_e_kawica'),
    array('Łochów', 'l_ocho_w'),
    array('Łodygowice', 'l_odygowice'),
    array('Łomnica', 'l_omnica'),
    array('Łozy', 'l_ozy'),
    array('Łupawa', 'l_upawa'),
    array('Łysa Polana', 'l_ysa_polana'),
    array('Maków Mazowiecki', 'mako_w_mazowiecki'),
    array('Malczyce', 'malczyce'),
    array('Maldanin', 'maldanin'),
    array('Malowa Góra', 'malowa_go_ra'),
    array('Małkinia', 'mal_kinia'),
    array('Michalów', 'michalo_w'),
    array('Michałów', 'michal_o_w'),
    array('Mieduniszki', 'mieduniszki'),
    array('Mielec 2', 'mielec_2'),
    array('Mietków', 'mietko_w'),
    array('Międzychód', 'mie_dzycho_d'),
    array('Międzylesie', 'mie_dzylesie'),
    array('Mikuszowice', 'mikuszowice'),
    array('Miłoszewo', 'mil_oszewo'),
    array('Mirków', 'mirko_w'),
    array('Mirsk', 'mirsk'),
    array('Mizerów-Borki', 'mizero_w_borki'),
    array('Mniszek', 'mniszek'),
    array('Mocha', 'mocha'),
    array('Modlin', 'modlin'),
    array('Morawica', 'morawica'),
    array('Mosina', 'mosina'),
    array('Mościsko', 'mos_cisko'),
    array('Mszana Dolna', 'mszana_dolna'),
    array('Muszyna Milik', 'muszyna_milik'),
    array('Nakło-Zachód', 'nakl_o_zacho_d'),
    array('Namysłów', 'namysl_o_w'),
    array('Narew', 'narew'),
    array('Narewka', 'narewka'),
    array('Niechmirów', 'niechmiro_w'),
    array('Niedzica', 'niedzica'),
    array('Nielisz', 'nielisz'),
    array('Niemodlin', 'niemodlin'),
    array('Nienowice', 'nienowice'),
    array('Nietków', 'nietko_w'),
    array('Nietulisko Duże', 'nietulisko_duz_e'),
    array('Nisko', 'nisko'),
    array('Niwka', 'niwka'),
    array('Niwki', 'niwki'),
    array('Nowa Pasłęka', 'nowa_pasl_e_ka'),
    array('Nowa Sól', 'nowa_so_l'),
    array('Nowa Wieś Podgórna', 'nowa_wies__podgo_rna'),
    array('Nowe Batorowo (Nowakowo)', 'nowe_batorowo_nowakowo'),
    array('Nowe Drezdenko', 'nowe_drezdenko'),
    array('Nowe Miasto', 'nowe_miasto'),
    array('Nowe Miasto Lubawskie', 'nowe_miasto_lubawskie'),
    array('Nowe Sadłuki', 'nowe_sadl_uki'),
    array('Nowogrodziec', 'nowogrodziec'),
    array('Nowogród', 'nowogro_d'),
    array('Nowogród Bobrzański', 'nowogro_d_bobrzan_ski'),
    array('Nowosielce', 'nowosielce'),
    array('Nowosiółki', 'nowosio_l_ki'),
    array('Nowy Dwór Gdański', 'nowy_dwo_r_gdan_ski'),
    array('Nowy Sącz_Dunajec', 'nowy_sa_cz_dunajec'),
    array('Nowy Sącz_Kamienica', 'nowy_sa_cz_kamienica'),
    array('Nowy Sącz_Łubinka', 'nowy_sa_cz_l_ubinka'),
    array('Nowy Targ', 'nowy_targ'),
    array('Nowy Targ-Kowaniec', 'nowy_targ_kowaniec'),
    array('Nysa', 'nysa'),
    array('Oborniki', 'oborniki'),
    array('Odolanów', 'odolano_w'),
    array('Odrzywół', 'odrzywo_l_'),
    array('Ojców', 'ojco_w'),
    array('Okocim (Lsop)', 'okocim_lsop'),
    array('Olchowce', 'olchowce'),
    array('Olsztyn-Kortowo', 'olsztyn_kortowo'),
    array('Olza', 'olza'),
    array('Oława', 'ol_awa'),
    array('Ołobok', 'ol_obok'),
    array('Opole-Groszowice', 'opole_groszowice'),
    array('Orzechowo', 'orzechowo'),
    array('Osetno', 'osetno'),
    array('Osielec', 'osielec'),
    array('Osjaków', 'osjako_w'),
    array('Osłonka', 'osl_onka'),
    array('Osowiec ', 'osowiec_'),
    array('Ostrołęka', 'ostrol_e_ka'),
    array('Ostróda', 'ostro_da'),
    array('Ostróżno', 'ostro_z_no'),
    array('Osuchy', 'osuchy'),
    array('Oświęcim', 'os_wie_cim'),
    array('Ozimek', 'ozimek'),
    array('Pakość', 'pakos_c_'),
    array('Pasłęk', 'pasl_e_k'),
    array('Pewel Mała', 'pewel_mal_a'),
    array('Piaseczno 2', 'piaseczno_2'),
    array('Piątnica', 'pia_tnica'),
    array('Piątnica-Łomża', 'pia_tnica_l_omz_a'),
    array('Piechowice', 'piechowice'),
    array('Pierzchały ', 'pierzchal_y_'),
    array('Pierzchały_2', 'pierzchal_y_2'),
    array('Pilchowice', 'pilchowice'),
    array('Piła', 'pil_a'),
    array('Pińczów', 'pin_czo_w'),
    array('Pisz', 'pisz'),
    array('Piwonice', 'piwonice'),
    array('Piwoń', 'piwon_'),
    array('Pleśno', 'ples_no'),
    array('Ploski', 'ploski'),
    array('Poddębice', 'podde_bice'),
    array('Podgórze', 'podgo_rze'),
    array('Podgórzyn', 'podgo_rzyn'),
    array('Podkępie', 'podke_pie'),
    array('Polana', 'polana'),
    array('Połaniec', 'pol_aniec'),
    array('Połęcko', 'pol_e_cko'),
    array('Popędzynka', 'pope_dzynka'),
    array('Popowo', 'popowo'),
    array('Poraj', 'poraj'),
    array('Porajów', 'porajo_w'),
    array('Poronin', 'poronin'),
    array('Posoka', 'posoka'),
    array('Poznań-Most Rocha', 'poznan__most_rocha'),
    array('Prosna', 'prosna'),
    array('Prostki', 'prostki'),
    array('Proszówki', 'proszo_wki'),
    array('Prudnik', 'prudnik'),
    array('Pruszcz Gdański', 'pruszcz_gdan_ski'),
    array('Pruszcz Gdański Kanał', 'pruszcz_gdan_ski_kanal_'),
    array('Prynowo', 'prynowo'),
    array('Przechody', 'przechody'),
    array('Przeczyce', 'przeczyce'),
    array('Przedbórz', 'przedbo_rz'),
    array('Przemyśl', 'przemys_l'),
    array('Przewoźniki', 'przewoz_niki'),
    array('Przewóz', 'przewo_z'),
    array('Przystań', 'przystan_'),
    array('Pszczyna', 'pszczyna'),
    array('Ptaki', 'ptaki'),
    array('Ptusza', 'ptusza'),
    array('Puck', 'puck'),
    array('Puławy', 'pul_awy'),
    array('Puławy-Azoty', 'pul_awy_azoty'),
    array('Pustków', 'pustko_w'),
    array('Pustynia', 'pustynia'),
    array('Pyskowice', 'pyskowice'),
    array('Pyskowice-Dzierżno', 'pyskowice_dzierz_no'),
    array('Pyzdry', 'pyzdry'),
    array('Rabka 2', 'rabka_2'),
    array('Racibórz-Miedonia', 'racibo_rz_miedonia'),
    array('Racławice Śląskie', 'racl_awice_s_la_skie'),
    array('Radocha', 'radocha'),
    array('Radomyśl', 'radomys_l'),
    array('Radziszów', 'radziszo_w'),
    array('Rajcza', 'rajcza'),
    array('Rajgród ', 'rajgro_d_'),
    array('Raków', 'rako_w'),
    array('Resko', 'resko'),
    array('Ręczyn', 're_czyn'),
    array('Rodzone', 'rodzone'),
    array('Rogożek', 'rogoz_ek'),
    array('Rogóźno', 'rogo_z_no'),
    array('Rogóźno 2', 'rogo_z_no_2'),
    array('Ropa', 'ropa'),
    array('Ruda Jastkowska', 'ruda_jastkowska'),
    array('Ruda Kozielska', 'ruda_kozielska'),
    array('Rudze', 'rudze'),
    array('Rybnik-Gotartowice', 'rybnik_gotartowice'),
    array('Rybnik-Stodoły', 'rybnik_stodol_y'),
    array('Rybotycze', 'rybotycze'),
    array('Rydzyna', 'rydzyna'),
    array('Rzepin', 'rzepin'),
    array('Rzeszotary', 'rzeszotary'),
    array('Rzeszów', 'rzeszo_w'),
    array('Rzuchów', 'rzucho_w'),
    array('Rzymówka', 'rzymo_wka'),
    array('Samarzewo', 'samarzewo'),
    array('Sandomierz', 'sandomierz'),
    array('Santok', 'santok'),
    array('Sarzyna', 'sarzyna'),
    array('Sępopol', 'se_popol'),
    array('Siemianówka', 'siemiano_wka'),
    array('Sieniawa', 'sieniawa'),
    array('Sieniawka', 'sieniawka'),
    array('Sieradz', 'sieradz'),
    array('Sierosławice', 'sierosl_awice'),
    array('Skawica Dolna', 'skawica_dolna'),
    array('Skoczów', 'skoczo_w'),
    array('Skorogoszcz', 'skorogoszcz'),
    array('Skwierzyna', 'skwierzyna'),
    array('Sławsk', 'sl_awsk'),
    array('Słowik', 'sl_owik'),
    array('Słubice', 'sl_ubice'),
    array('Słupsk', 'sl_upsk'),
    array('Smolajny', 'smolajny'),
    array('Smolice', 'smolice'),
    array('Smołdzino', 'smol_dzino'),
    array('Smukała', 'smukal_a'),
    array('Sobianowice', 'sobianowice'),
    array('Sochonie', 'sochonie'),
    array('Sokołda', 'sokol_da'),
    array('Sosnówka', 'sosno_wka'),
    array('Soszyca', 'soszyca'),
    array('Spała', 'spal_a'),
    array('Sromowce Wyżne', 'sromowce_wyz_ne'),
    array('Staniszcze Wielkie', 'staniszcze_wielkie'),
    array('Stargard', 'stargard'),
    array('Stary Kraków', 'stary_krako_w'),
    array('Stary Raduszec', 'stary_raduszec'),
    array('Stary Sącz', 'stary_sa_cz'),
    array('Staszów', 'staszo_w'),
    array('Stradomka', 'stradomka'),
    array('Strękowa Góra', 'stre_kowa_go_ra'),
    array('Stróża', 'stro_z_a'),
    array('Strzyżów', 'strzyz_o_w'),
    array('Stuposiany', 'stuposiany'),
    array('Sucha Beskidzka', 'sucha_beskidzka'),
    array('Suchy Dąb', 'suchy_da_b'),
    array('Sulejów (Kopalnia)', 'sulejo_w_kopalnia'),
    array('Supraśl', 'supras_l'),
    array('Suraż', 'suraz_'),
    array('Szabelnia', 'szabelnia'),
    array('Szaflary', 'szaflary'),
    array('Szalejów Dolny', 'szalejo_w_dolny'),
    array('Szczawne', 'szczawne'),
    array('Szczecin Most Długi', 'szczecin_most_dl_ugi'),
    array('Szczecin Podjuchy', 'szczecin_podjuchy'),
    array('Szczerców', 'szczerco_w'),
    array('Szczucin', 'szczucin'),
    array('Szkwa', 'szkwa'),
    array('Szprotawa', 'szprotawa'),
    array('Szreńsk', 'szren_sk'),
    array('Sztabin', 'sztabin'),
    array('Szypry', 'szypry'),
    array('Ścinawa', 's_cinawa'),
    array('Ślęza', 's_le_za'),
    array('Śrem', 's_rem'),
    array('Świebodzice', 's_wiebodzice'),
    array('Świerkocin', 's_wierkocin'),
    array('Świerzawa', 's_wierzawa'),
    array('Świnoujście', 's_winoujs_cie'),
    array('Tchórzew', 'tcho_rzew'),
    array('Tczew', 'tczew'),
    array('Terka', 'terka'),
    array('Tłumaczów', 'tl_umaczo_w'),
    array('Tokarnia', 'tokarnia'),
    array('Tolkmicko', 'tolkmicko'),
    array('Tomaryny', 'tomaryny'),
    array('Topoliny', 'topoliny'),
    array('Toruń', 'torun_'),
    array('Trawniki', 'trawniki'),
    array('Trąbczyn', 'tra_bczyn'),
    array('Trestno', 'trestno'),
    array('Trybsz 2', 'trybsz_2'),
    array('Tryńcza', 'tryn_cza'),
    array('Trzciniec', 'trzciniec'),
    array('Trzebiatów', 'trzebiato_w'),
    array('Trzebież', 'trzebiez_'),
    array('Tuchola', 'tuchola'),
    array('Tujsk', 'tujsk'),
    array('Turawa', 'turawa'),
    array('Turoszów', 'turoszo_w'),
    array('Tychówko', 'tycho_wko'),
    array('Tylmanowa', 'tylmanowa'),
    array('Ujsoły', 'ujsol_y'),
    array('Ujście', 'ujs_cie'),
    array('Ujście Nysy Kłodzkiej', 'ujs_cie_nysy_kl_odzkiej'),
    array('Uniejów', 'uniejo_w'),
    array('Ustka', 'ustka'),
    array('Ustroń-Obłaziec', 'ustron__obl_aziec'),
    array('Wadowice', 'wadowice'),
    array('Walery', 'walery'),
    array('Wampierzów', 'wampierzo_w'),
    array('Warszawa', 'warszawa'),
    array('Warszawa-Nadwilanówka Śl', 'warszawa_nadwilano_wka_s_l'),
    array('Wąchock', 'wa_chock'),
    array('Wąsosz', 'wa_sosz'),
    array('Wejherowo', 'wejherowo'),
    array('Węgorzewo', 'we_gorzewo'),
    array('Widawa', 'widawa'),
    array('Widuchowa', 'widuchowa'),
    array('Wilkanów', 'wilkano_w'),
    array('Winnica', 'winnica'),
    array('Wisła', 'wisl_a'),
    array('Wisła-Czarne', 'wisl_a_czarne'),
    array('Wisła-Czarne (Biała Wisełka)', 'wisl_a_czarne_bial_a_wisel_ka'),
    array('Wisła-Czarne (Czarna Wisełka)', 'wisl_a_czarne_czarna_wisel_ka'),
    array('Wiślina', 'wis_lina'),
    array('Wizna', 'wizna'),
    array('Władysławowo', 'wl_adysl_awowo'),
    array('Włochy', 'wl_ochy'),
    array('Włocławek', 'wl_ocl_awek'),
    array('Włodawa', 'wl_odawa'),
    array('Wojanów', 'wojano_w'),
    array('Wolin', 'wolin'),
    array('Wólka Mlądzka', 'wo_lka_mla_dzka'),
    array('Wronki', 'wronki'),
    array('Wychódźc', 'wycho_dz_c'),
    array('Wyrzysk', 'wyrzysk'),
    array('Wyszków', 'wyszko_w'),
    array('Wyszogród', 'wyszogro_d'),
    array('Zabrzeg', 'zabrzeg'),
    array('Zabuże', 'zabuz_e'),
    array('Zagórz', 'zago_rz'),
    array('Zagrodno', 'zagrodno'),
    array('Zakłodzie', 'zakl_odzie'),
    array('Zakopane-Harenda', 'zakopane_harenda'),
    array('Zaliwie-Piegawki', 'zaliwie_piegawki'),
    array('Zambski Kościelne', 'zambski_kos_cielne'),
    array('Zapałów', 'zapal_o_w'),
    array('Zaruzie', 'zaruzie'),
    array('Zator', 'zator'),
    array('Zatwarnica', 'zatwarnica'),
    array('Zawady', 'zawady'),
    array('Zawady ', 'zawady_'),
    array('Zawichost', 'zawichost'),
    array('Zboiska', 'zboiska'),
    array('Zborowice', 'zborowice'),
    array('Zbytowa', 'zbytowa'),
    array('Zgłobice', 'zgl_obice'),
    array('Zgorzelec', 'zgorzelec'),
    array('Żabnica', 'z_abnica'),
    array('Żabno', 'z_abno'),
    array('Żagań', 'z_agan_'),
    array('Żarnowa', 'z_arnowa'),
    array('Żelazno', 'z_elazno'),
    array('Żółków', 'z_o_l_ko_w'),
    array('Żukowo', 'z_ukowo'),
    array('Żuków', 'z_uko_w'),
    array('Żywiec', 'z_ywiec'),
        /*
     *
     *
     */
    # JAKIEŚ POGODOWE
    array('wiatr'),
    array('stacja pomiarowa'),
    array('tlenek węgla', 'tlenek_we_gla'),
    array('pył zawieszony Pe eM 10', 'pyl__zawieszony_pm10'),
    array('benzen', 'benzen'),
    array('dwutlenek azotu', 'dwutlenek_azotu'),
    array('pył zawieszony Pe eM 2.5', 'pyl__zawieszony_pm25'),
    array('dwutlenek siarki', 'dwutlenek_siarki'),
    array('ozon', 'ozon'),
    array('Wrocław - Bartnicza', 'wrocl_aw___bartnicza'),
    array('Wrocław - Korzeniowskiego', 'wrocl_aw___korzeniowskiego'),
    array('Wrocław - Wiśniowa', 'wrocl_aw___wis_niowa'),
    array('Legnica - Rzeczypospolitej', 'legnica___rzeczypospolitej'),
    array('Wałbrzych - Wysockiego', 'wal_brzych___wysockiego'),
    array('Czerniawa', 'czerniawa'),
    array('Działoszyn', 'dzial_oszyn'),
    array('Dzierżoniów - Piłsudskiego', 'dzierz_onio_w___pil_sudskiego'),
    array('Kłodzko - Szkolna', 'kl_odzko___szkolna'),
    array('Nowa Ruda - Srebrna', 'nowa_ruda___srebrna'),
    array('Oława - Żołnierzy AKa', 'ol_awa___z_ol_nierzy_ak'),
    array('Osieczów', 'osieczo_w'),
    array('Śnieżka', 's_niez_ka'),
    array('Ząbkowice Śląskie', 'za_bkowice_s_la_skie'),
    array('Zgorzelec - Bohaterów Getta', 'zgorzelec___bohatero_w_getta'),
    array('Jelenia Góra - Ogińskiego', 'jelenia_go_ra___ogin_skiego'),
    array('Lądek-Zdrój', 'la_dek_zdro_j'),
    array('Lubań', 'luban_'),
    array('Bydgoszcz Plac Poznański', 'bydgoszcz_plac_poznan_ski'),
    array('Bydgoszcz Warszawska', 'bydgoszcz_warszawska'),
    array('Łódź-Widzew', 'l_o_dx__widzew'),
    array('Łódź-Gdańska 16', 'l_o_dx__gdan_ska_16'),
    array('Pabianice-Polfa', 'pabianice_polfa'),
    array('Zgierz-Śródmieście', 'zgierz_s_ro_dmies_cie'),
    array('Łódź-Jana Pawła drugiego piętnaście', 'l_o_dx__jana_pawl_a_ii_15'),
    array('Gajew', 'gajew'),
    array('Parzniewice', 'parzniewice'),
    array('Piotrków Tryb.-Krakowskie Przedmieście', 'piotrko_w_tryb_krakowskie_przedmies_cie'),
    array('Radomsko-Rolna 2', 'radomsko_rolna2'),
    array('Żyrardów-Roosevelta', 'z_yrardo_w_roosevelta'),
    array('Guty Duże', 'guty_duz_e'),
    array('Konstancin-Jeziorna-Wierzejewskiego', 'konstancin_jeziorna_wierzejewskiego'),
    array('Opole manualna 4', 'opole_manualna_4'),
    array('Opole automat 5', 'opole_automat_5'),
    array('Kędzierzyn-Koźle automat 1', 'k_kox_le_automat_1'),
    array('Olesno automat 4', 'olesno_automat_4'),
    array('Zdzieszowice automat 2', 'zdzieszowice_automat_2'),
    array('Rzeszów-Nowe Miasto', 'rzeszo_w_nowe_miasto'),
    array('Jaslo-Sikorskiego', 'jaslo_sikorskiego_wios'),
    array('Nisko-Szklarniowa-', 'nisko_szklarniowa_wios'),
    array('Przemysl-Grunwaldzka-WIOS', 'przemysl_grunwaldzka_wios'),
    array('WIOŚ Gołdap ulica Jaćwieska', 'wios__gol_dap_ul_jac_wieska'),
    array('KMŚ Puszcza Borecka', 'kms__puszcza_borecka'),
    array('WIOŚ Ełk', 'wios__el_k'),
    array('WIOŚ Ostróda Piłsudskiego', 'wios__ostro_da_pil_sudskiego'),
    array('Poznan-Polanka', 'poznan_polanka'),
    array('Poznan-Dabrowskiego', 'poznan_dabrowskiego'),
    array('Kalisz-Wyszynskiego', 'kalisz_wyszynskiego'),
    array('Konin-Wyszynskiego', 'konin_wyszynskiego'),
    array('Pila, ulica Kusocinkiego', 'pila_ul_kusocinkiego'),
    array('Piaski-Krzyzowka', 'piaski_krzyzowka'),
    array('Borowiec-Drapalka', 'borowiec_drapalka'),
    array('Kozieglowy-osiedle Lesne', 'kozieglowy_oslesne'),
    array('Szczecin_Andrzejewskiego', 'szczecin_andrzejewskiego'),
    array('Szczecin_Piłsudskiego', 'szczecin_pil_sudskiego'),
    array('Szczecin_Łączna', 'szczecin_l_a_czna'),
    array('Koszalin_ArmiiKrajowej', 'koszalin_armiikrajowej'),
    array('Widuchowa', 'widuchowa'),
    array('Szczecinek_Przemysłowa', 'szczecinek_przemysl_owa'),
    array('Dąbrowa Górnicza, Tysiąclecia 25', 'da_browa_go_rnicza_ul_tysia_clecia_25a'),
    array('Gliwice, ulica Mewy 34', 'gliwice_ul_mewy_34'),
    array('Katowice, ulica Plebiscytowa/A4', 'katowice_ul_plebiscytowa/a4'),
    array('Katowice, ulica Kossutha 6', 'katowice_ul_kossutha_6'),
    array('Sosnowiec, ulica Lubelska 51', 'sosnowiec_ul_lubelska_51'),
    array('Tychy, ulica Tołstoja 1', 'tychy_ul_tol_stoja_1'),
    array('Rybnik, ulica Borki 37 d', 'rybnik_ul_borki_37_d'),
    array('Żory, Sikorskiego 52', 'z_ory_os_gen_wl_adysl_awa_sikorskiego_52_2'),
    array('Bielsko-Biała, ulica Kossak-Szczuckiej 19', 'bielsko_bial_a_ul_kossak_szczuckiej_19'),
    array('Częstochowa, ulica Jana Pawła drugiego', 'cze_stochowa_ul_ak/jana_pawl_a_ii'),
    array('Częstochowa, ulica Baczyńskiego 2', 'cze_stochowa_ul_baczyn_skiego_2'),
    array('Cieszyn, ulica Mickiewicza 13', 'cieszyn_ul_mickiewicza_13'),
    array('Ustroń, ulica Sanatoryjna 7', 'ustron__ul_sanatoryjna_7'),
    array('Wodzisław Śląski, ulica Gałczyńskiego 1', 'wodzisl_aw_s_la_ski_ul_gal_czyn_skiego_1'),
    array('Złoty Potok, Leśniczówka', 'zl_oty_potok_les_niczo_wka'),
    array('Żywiec, ulica Kopernika  83', 'z_ywiec_ul_kopernika__83_a'),
    array('Czerwionka-Leszczyny, ulica Kopalniana', 'czerwionka_leszczyny_ul_kopalniana'),
    array('Kielce, ulica Jagiellońska', 'kielce_ul_jagiellon_ska'),
    array('Nowiny, ulica Parkowa', 'nowiny_ul_parkowa'),
    array('Połaniec, ulica Ruszczańska', 'pol_aniec_ul_ruszczan_ska'),
    array('Starachowice, ulica Złota', 'starachowice_ul_zl_ota'),
    array('Końskie, MOBILNA', 'kon_skie_mobilna'),
    array('Małogoszcz, ulica Słoneczna', 'mal_ogoszcz_ul_sl_oneczna'),
    array('WIOŚ Olsztyn ulica Puszkina', 'wios__olsztyn_ul_puszkina'),
    array('WIOŚ Elbląg ulica Bażyńskiego', 'wios__elbla_g_ul_baz_yn_skiego'),
    array('Kraków, Aleja Krasińskiego', 'krako_w_aleja_krasin_skiego'),
    array('Kraków, ulica Bujaka', 'krako_w_ul_bujaka'),
    array('Kraków, ulica Bulwarowa', 'krako_w_ul_bulwarowa'),
    array('Kraków, ulica Dietla', 'krako_w_ul_dietla'),
    array('Kraków, ulica Złoty Róg', 'krako_w_ul_zl_oty_ro_g'),
    array('Kraków, osiedle Piastów', 'krako_w_os_piasto_w'),
    array('Kraków, ulica Telimeny', 'krako_w_ul_telimeny'),
    array('Kraków, osiedle Wadów', 'krako_w_os_wado_w'),
    array('Tarnów, ulica Bitwy pod Studziankami', 'tarno_w_ul_bitwy_pod_studziankami'),
    array('Tarnów, ulica Ks. Romana Sitko', 'tarno_w_ul_ks_romana_sitko'),
    array('Nowy Sącz, ulica Nadbrzeżna', 'nowy_sa_cz_ul_nadbrzez_na'),
    array('Krempna-MPN-WIOS', 'krempna_mpn_wios'),
    array('Rymanów-Zdrój-Samorząd', 'rymano_w_zdro_j_samorza_d'),
    array('Mielec-Biernackiego-WIOS', 'mielec_biernackiego_wios'),
    array('Białystok-Miejska', 'bial_ystok_miejska'),
    array('Białystok-Warszawska', 'bial_ystok_warszawska'),
    array('Borsukowizna-Wiejska', 'borsukowizna_wiejska'),
    array('Lomza Sikorskiego 48/94', 'lomza_sikorskiego_48/94'),
    array('Augustów - mobilne ', 'augusto_w___mobilne_'),
    array('Gdańsk Śródmieście', 'am1_gdan_sk_s_ro_dmies_cie'),
    array('Gdańsk Stogi', 'am2_gdan_sk_stogi'),
    array('Gdańsk Nowy Port', 'am3_gdan_sk_nowy_port'),
    array('Gdynia Pogórze', 'am4_gdynia_pogo_rze'),
    array('Gdańsk Szadółki', 'am5_gdan_sk_szado_l_ki'),
    array('Sopot', 'am6_sopot'),
    array('Gdańsk Wrzeszcz', 'am8_gdan_sk_wrzeszcz'),
    array('Gdynia Dąbrowa', 'am9_gdynia_da_browa'),
    array('Gdynia Śródmieście', 'am10_gdynia_s_ro_dmies_cie'),
    array('Słupsk Kniaziewicza', 'am11_sl_upsk_kniaziewicza'),
    array('Kościerzyna Targowa', 'am12_kos_cierzyna_targowa'),
    array('Malbork Mickiewicza', 'am15_malbork_mickiewicza'),
    array('Lębork Malczewskiego', 'am16_le_bork_malczewskiego'),
    array('Liniewko Kościerskie', 'am17_liniewko_kos_cierskie'),
    array('IMGW Łeba - Rąbka', 'imgw_l_eba___ra_bka'),
    array('Olkusz, ulica Francesco Nullo', 'olkusz_ul_francesco_nullo'),
    array('Skawina, osiedle Ogrody', 'skawina_os_ogrody'),
    array('Szymbark', 'szymbark'),
    array('Trzebinia, osiedle Związku Walki Młodych', 'trzebinia_os_zwia_zku_walki_ml_odych'),
    array('Zakopane, ulica Sienkiewicza', 'zakopane_ul_sienkiewicza'),
    array('Szarów, ulica Spokojna', 'szaro_w_ul_spokojna'),
    array('Kaszów', 'kaszo_w'),
    array('Sucha Beskidzka, ulica Nieszczyńskiej', 'sucha_beskidzka_ul_nieszczyn_skiej'),
    array('Nowy Targ, Plac Słowackiego', 'nowy_targ_plac_sl_owackiego'),
    array('Warszawa-Komunikacyjna', 'warszawa_komunikacyjna'),
    array('Warszawa-Podleśna', 'warszawa_podles_na'),
    array('Warszawa-Tołstoja', 'warszawa_tol_stoja'),
    array('Warszawa-Marszałkowska', 'warszawa_marszal_kowska'),
    array('Warszawa-Ursynów', 'warszawa_ursyno_w'),
    array('Warszawa-Targówek', 'warszawa_targo_wek'),
    array('Płock-Gimnazjum', 'pl_ock_gimnazjum'),
    array('Płock-Reja', 'pl_ock_reja'),
    array('Radom-Tochtermana', 'radom_tochtermana'),
    array('Belsk-IGFPAN', 'belsk_igfpan'),
    array('Granica-KPN', 'granica_kpn'),
    array('Legionowo-Zegrzyńska', 'legionowo_zegrzyn_ska'),
    array('Piastów-Pułaskiego', 'piasto_w_pul_askiego'),
    array('Siedlce-Konarskiego', 'siedlce_konarskiego'),
    array('Lublin ulica Obywatelska', 'lublin_ul_obywatelska'),
    array('IMGW-Jarczew', 'imgw_jarczew'),
    array('Lublin-Podmiejska', 'lublin_podmiejska'),
    array('Zamość ulica Hrubieszowska 69A', 'zamos_c__ul_hrubieszowska_69a'),
    array('Gorzów Wlkp. ulica Kosynierów Gdyńskich', 'gorzo_w_wlkp_ul_kosyniero_w_gdyn_skich'),
    array('Zielona Góra ulica Krótka', 'zielona_go_ra_ul_kro_tka'),
    array('Smolary Bytnickie', 'smolary_bytnickie'),
    array('Sulęcin ulica Dudka', 'sule_cin_ul_dudka'),
    array('Wschowa ulica Kazimierza Wielkiego', 'wschowa_ul_kazimierza_wielkiego'),
    array('Żary, ulica Szymanowskiego 8', 'z_ary_ul_szymanowskiego_8'),
    array('Toruń Airpointer', 'torun__airpointer'),
    array('Toruń POLICJA', 'torun__policja'),
    array('Włocławek OKRZEI', 'wl_ocl_awek_okrzei'),
    array('Grudziądz Airpointer', 'grudzia_dz_airpointer'),
    array('Inowrocław Airpointer', 'inowrocl_aw_airpointer'),
    array('Ciechocinek', 'ciechocinek'),
    array('Koniczynka', 'koniczynka'),
    array('Bory Tucholskie', 'bory_tucholskie'),
    /*
     *
     *
     */
    # jakies inne pogodowe
    array('zachmurzenie umiarkowane możliwe burze i opady deszczu', 'zachmurzenie_umiarkowane__mo_liwe_burze_i_opady_deszczu'),
    array('zachmurzenie umiarkowane możliwe burze', 'zachmurzenie_umiarkowane__mo_liwe_burze'),
    array('zachmurzenie umiarkowane z opadami deszczu', 'zachmurzenie_umiarkowane_z_opadami_deszczu'),
    array('pochmurno z opadami deszczu', 'pochmurno_z_opadami_deszczu'),
    array('całkowite zachmurzenie','calkowite_zachmurzenie'),
    array('pochmurno możliwe burze','pochmurno__mo_liwe_burze'),
    array('pochmurno z opadami deszczu ze śniegiem','pochmurno_z_opadami_deszczu_ze__niegiem'),
    array('pochmurno z opadami śniegu','pochmurno_z_opadami__niegu'),
    array('pochmurno z przelotnymi opadami śniegu','pochmurno_z_przelotnymi_opadami_deszczu'),
    array('prawie bezchmurnie','prawie_bezchmurnie'),
    array('przejaśnienia zachmurzenie umiarkowane','przejas_nienia__zachmurzenie_umiarkowane'),
    array('słonecznie','s_onecznie'),
    array('zachmurzenie umiarkowane z opadami deszczu ze śniegiem','zachmurzenie_umiarkowane_z_opadami_deszczu_ze__niegiem'),
    array('zachmurzenie umiarkowane z opadami śniegu','zachmurzenie_umiarkowane_z_opadami__niegu'),
    array('zachmurzenie umiarkowane z przelotnymi opadami deszczu','zachmurzenie_umiarkowane_z_przelotnymi_opadami_deszczu'),
);

