'01-01':'Mieczysław Mieszko Maria Mieczysława Masław Odyseusz Wilhelm',
'01-02':'Abel Bazyli Narcyz Grzegorz Izydor Makary Odylon',
'01-03':'Arleta Daniel Danuta Enoch Genowefa Piotr',
'01-04':'Aniela Benedykta Dobromir Eugeniusz Grzegorz Izabela Leonia Tytus',
'01-05':'Amata Amato Emilian Emiliusz Hanna Edward Szymon Symeon',
'01-06':'Andrzej Balcer Baltazar Epifania Kacper Melchior Norman',
'01-07':'Chociesław Izydor Julian Chocsław Lucjan Oriana Rajmund Walenty',
'01-08':'Arlena Mścisław Seweryn Teofil',
'01-09':'Antoni Julian Marcelina Marcjanna',
'01-10':'Agaton Danuta Dobrosław Jan Kolumba Nikanor Paweł Wilhelm',
'01-11':'Feliks Hilary Honorata Hygin Matylda Odon',
'01-12':'Antoni Arkadiusz Bonet Arkady Benedykt Bonitus Czesława Bonita Ernest Greta',
'01-13':'Bogumił Bogumiła Bogusław Gotfryd Leoncjusz Melania Weronika',
'01-14':'Feliks Hilary Amadea Nina Odo Rajner.',
'01-15':'Aleksander Dąbrówka Dobrawa Domosław Izydor Makary Maur Paweł',
'01-16':'Marceli Waldemar Waleriusz Treweriusz Włodzimierz',
'01-17':'Antoni Jan Alba Rościsław Aleks',
'01-18':'Beatrycze Bogumił Krystyna Liberata Małgorzata Piotr',
'01-19':'Andrzej Bernard Erwin Erwina Eufemia Henryk Kanut Mariusz Marta Matylda Sara Wulstan',
'01-20':'Dobiegniew Fabian Sebastian',
'01-21':'Agnieszka Patrokles Epifani Jarosław Jarosława Marcela',
'01-22':'Anastazja Anastazy Dorian Gaudencjusz Gaudenty Wincenty',
'01-23':'Emerencja Ildefons Jan Klemens Maria Rajmund Rajmunda',
'01-24':'Chwalibog Franciszek Milena Rafaela Rafał Tymoteusz',
'01-25':'Miłosz Paweł Tacjana Artemia',
'01-26':'Polikarp Skarbimir Leon Tymoteusz Tytus Leona Wanda',
'01-27':'Angela Aniela Ilona Jan Chryzostom Jerzy Julian Przybysław',
'01-28':'Agnieszka Augustyn Flawian Ildefons Julian Karol Piotr Roger Tomasz Waleriusz Walery',
'01-29':'Franciszek Salezy Hanna Ismena Gildas Konstancja Waleriusz Zdzisław',
'01-30':'Adelajda Cyntia Dobiegniew Feliks Gerard Gerarda Gerhard Hiacynta Maciej Marcin Martyna Sebastian Teofil ',
'01-31':'Cyrus Euzebiusz Jan Ksawery Ludwik Marceli Marcelin Marcelina Piotr',
'02-01':'Brygida Dobrochna Seweryn Żegota',
'02-02':'Joanna Katarzyna Kornel Maria Miłosław Miłosława Mirosław Marian',
'02-03':'Błażej Oskar Leoniusz Ignacy',
'02-04':'Joanna Weronika',
'02-05':'Adelajda Agata',
'02-06':'Dorota Leon Paweł Leona',
'02-07':'Ryszard Teodor',
'02-08':'Elfryda Hieronim Ampeliusz Gabriela Sebastian Izajasz',
'02-09':'Apolonia Cyryl Marian Sulisława',
'02-10':'Jacek Scholastyka',
'02-11':'Dezydery Lucjan Olgierd Cedmon',
'02-12':'Modest Eulalia Damian Ampeliusz',
'02-13':'Grzegorz Katarzyna',
'02-14':'Cyryl Dobiesława Metody Auksencja Auksencjusz Auksenty Liliany',
'02-15':'Jowita Faustyn Zygfryda Zygfryd',
'02-16':'Danuta Eliasz Julianna Izajasz',
'02-17':'Aleksy Donat Zbigniew',
'02-18':'Konstancja Szymon',
'02-19':'Arnold Konrad',
'02-20':'Leon Ludomira Leona',
'02-21':'Eleonora Piotr Gumbert',
'02-22':'Małgorzata Konkordia Wrocisław',
'02-23':'Damian Izabella Polikarp Marta',
'02-24':'Jaśmina Józefa Bogurad Sergiusz Maciej Marek',
'02-25':'Cezary Wiktor',
'02-26':'Aleksander Dionizy Mirosław',
'02-27':'Gabriel Auksencja Baldomer Auksencjusz Auksenty Baldomera',
'02-28':'Ludomir Roman Makary Oswald',
'02-29':'Ariusz Roman Dobronieg Lutosław Teofil',
'03-01':'Feliks Herakles Józef Eudoksja Leon Nikifor Leona Antoni Piotr Joanna Antonina Radosław Budzisław Albina',
'03-02':'Absalon Paweł Januaria Symplicjusz Michał Helena Piotr Halszka Franciszek Henryk Krzysztof',
'03-03':'Wirzchosława Gerwina Asteriusz Gerwin Kinga Maryna Kunegunda Tycjan',
'03-04':'Adrian Leonard Leonarda Lucjusz Eugeniusz Kazimierz Lucja Arkadiusz',
'03-05':'Adrian Fryderyk Pakosław Jan Oliwia Marek',
'03-06':'Eugenia Róża Agnieszka Koleta Frydolin Klaudian Wojsław Wiktor Jordan',
'03-07':'Paweł Polikarp Tomasz Nadmir Felicyta',
'03-08':'Miłogost Wincenty Stefan Filemon Jan Julian Beata',
'03-09':'Mścisława Dominik Tarazjusz Prudencjusz Franciszka Katarzyna Przemyślibor',
'03-10':'Makary Porfirion Marceli Cyprian Aleksander Zwnisława',
'03-11':'Benedykt Konstantyn Prokop Sofroniusz Trofim Kandyd Drogosława Konstanty',
'03-12':'Bernard Józefina Grzegorz Blizbor',
'03-13':'Roderyk Bożena Ewa Marek Kasjan Ernest Trzebiesław Krystyna Marek',
'03-14':'Fawila Michał Afrodyzy Pamela Bożeciecha Matylda Leona Afrodyzjusz Afrodyzja Leon Jakub',
'03-15':'Klemens Ludwika Longina Longin Gościmir Krzysztof',
'03-16':'Hilary Abraham Cyriak Hiacynt Izabela Artemia Natalis Herbert',
'03-17':'Patryk Patrycjusz Zbigniew Zbygniew Gerazym Zbygniewa Regina Patrycy Jan Gertruda',
'03-18':'Narcyz Boguchwał Anzelm Cyryl Marta Edward Salwator Aleksander Trofim',
'03-19':'Józef Sybilla Natasza',
'03-20':'Klemens Robert Klaudia Bogusław Ambroży Eufemia Cyriaka Wincenty Patrycjusz Anatol Aleksander Fotyna',
'03-21':'Benedykt Marzanna Elza Klemencja Mikołaj Filemon Lubomira',
'03-22':'Paweł Bogusław Bazylisa Kazimierz Katarzyna Godzisław',
'03-23':'Feliks Pelagia Zbysław Eberhard Konrad Zbyszko Piotr Pelagiusz Katarzyna Oktawian',
'03-24':'Sewer Sofroniusz Dzierżysława Marek Szymon Dzirżysława Gabriel',
'03-25':'Mariola Dyzma Wieńczysław Maria Lutomysł Ireneusz',
'03-26':'Feliks Emanuel Emanuela Teodor Larysa Nikifor Manuela Tworzymir',
'03-27':'Benedykt Rupert Ernest Lidia Jan',
'03-28':'Aniela Krzesisław Sykstus Antoni Jan',
'03-29':'Wiktoryn Marek Eustacjusz Czcirad Cyryl',
'03-30':'Leonard Amadea Kwiryna Kwiryn Mamertyn Aniela Litobor Częstobor Leonarda Jan Mamertyna',
'03-31':'Gwidon Beniamin Kornelia Dobromira Balbina Amos',
'04-01':'Hugo Chryzant Zbyszko Zbigniew Grażyna Teodora Katarzyna Tolisław',
'04-02':'Laurencja Franciszek Urban',
'04-03':'Ryszard Antoni Pankracy Cieszygor Jakub',
'04-04':'Benedykt Ambroży Zdzimir Izydor',
'04-05':'Irena Wincenty Borzywoj',
'04-06':'Sykstus Zachariasz Wilhelm Diogenes Zachary Katarzyna Ireneusz',
'04-07':'Donat Herman Przecław Epifaniusz Hegezyp Rufin',
'04-08':'Sieciesława Cezaryna Radosław Denis Apolinary Cezary January',
'04-09':'Marceli Matron Maja Dobrosława Wadim',
'04-10':'Grodzisław Makary Pompejusz Marek Apoloniusz Daniel Michał Antoni Ezechiel Małgorzata Henryk',
'04-11':'Filip Herman Leon Jaromir Gemma Leona',
'04-12':'Zenon Sabbas Andrzej Wiktor Juliusz',
'04-13':'Justyn Marcjusz Hermenegilda Przemysł Przemysław Małgorzata Jan Ida',
'04-14':'Walerian Justyn Tyburcja Berenika Tyburcy Maria Justyna Tyburcjusz Julianna Myślimir Trofim',
'04-15':'Wiktoryn Bazyli Olimpia Modest Wszegniew Anastazja Tytus',
'04-16':'Benedykt Bernadeta Charyzjusz Leonid Erwin Patrycy Lambert Urban Julia Ksenia',
'04-17':'Klara Józef Robert Radociech Anicet Stefan Izydora Aniceta Jakub Innocenty',
'04-18':'Gościsław Bogusław Apoloniusz Flawiusz Bogusława Alicja',
'04-19':'Konrada Leontyna Tymon Adolfa Werner Leona Włodzimierz Adolf Cieszyrad Leon Pafnucy',
'04-20':'Amalia Jagna Teodor Florenty Marcelina Agnieszka Florencjusz Nawoj Szymon Sulpicjusz Czesław',
'04-21':'Feliks Addar Anzelm Drogomił Apollo Irydion Apollina Bartosz Konrad',
'04-22':'Wanesa Kajus Teodor Soter Heliodor Leonid Strzeżymir Leon Leona',
'04-23':'Adalbert Wojciech Gerard Helena Jerzy Gabriela',
'04-24':'Fidelis Erwin Horacy Egbert Grzegorz Horacjusz Aleksja Aleksy Aleksander',
'04-25':'Kaliksta Ewodia Markusław Jarosław Ewodiusz Marek',
'04-26':'Marcelin Marcelina Maria Spycimir Klet Marzena Klaudiusz Artemon',
'04-27':'Felicja Anastazy Marcin Zyta Piotr Teofil Andrzej Kanizjusz Bożebor',
'04-28':'Paweł Maria Waleria Marek Przybycześć Afrodyzy Afrodyzjusz Afrodyzja Arystarch Andrea Witalis',
'04-29':'Hugo Bogusław Robert Piotr Paulin Ryta Augustyn Roberta Angelina Wiktor',
'04-30':'Eutropiusz Bartłomiej Chwalisława Lilla Katarzyna Afrodyzy Afrodyzjusz Afrodyzja Jakub Marian',
'05-01':'Jeremiasz Filip Briok Jeremi Józef Aniela Lubomir Jakub',
'05-02':'Zoja Zygmunta Walter Witomir Atanazy Walenty Zygmunt Anatol',
'05-03':'Mariola Maria Alodia Antonina Aleksander',
'05-04':'Florian Michał Paulin Monika Grzegorz January',
'05-05':'Pius Teodor Irena Zdziebor Penelopa Ita Waldemar Sabrina',
'05-06':'Judyta Ewodia Gościwit Benedykta Ewodiusz Jurand Jan',
'05-07':'Benedykt Florian Bogumir Gizela Ludomiła Wincenta Sabbas Domicela Domicjan Domicjana Flawia Róża',
'05-08':'Heladiusz Dezyderia Michał Piotr Stanisław',
'05-09':'Karolina Hiob Grzegorz Mikołaj Beat',
'05-10':'Gordian Chociesław Gordiana Symeon Chocsław Antonin Izydor Częstomir Wiktoryna Jan',
'05-11':'Benedykt Filip Mamerta Adalbert Leon Stella Franciszek Mamert Lutogniew Ignacy',
'05-12':'Wszemił Dominik Epifani Nawoja Domicjan Domicjana Joanna Pankracy Jazon Jan Domicela Flawia Janina Nawojka',
'05-13':'Robert Serwacy Aaron Magdalena Piotr Andrzej Natalis Gloria Ciechosław',
'05-14':'Jeremiasz Koryna Bonifacy Maciej Wiktor Dobiesław Ampeliusz',
'05-15':'Strzeżysław Robert Berta Cecyliusz Atanazy Zofia Dionizja Czcibora Nadzieja Izydor Jan',
'05-16':'Germeriusz Trzebiemysł Jan Nepomucen Ubald Wiktorian Andrzej Szymon Honorat Jędrzej Jan',
'05-17':'Weronika Paschalis Herakliusz Sławomir Bruno Wiktor',
'05-18':'Feliks Wenancjusz Myślibor Eryk Liberiusz Klaudia Aleksander Aleksandra Toska',
'05-19':'Celestyn Iwa Bernarda Piotr Iwo Pękosław Mikołaj Augustyn',
'05-20':'Teodor Anastazy Wiktoria Asteriusz Bazyli Bernardyn Saturnina Sabbas Iwo Sieciech Bronimir',
'05-21':'Tymoteusz Ryksa Ryksa Walenty Wiktor Kryspin Przedsława Jan Pudens',
'05-22':'Wisława Emil Helena Ryta Julia Jan Krzesisława Wiesław Wiesława',
'05-23':'Dezydery Iwona Symeon Michał Emilia Dezyderiusz Budziwoj Eufrozyna Jan',
'05-24':'Maria Wincenty Milena Joanna Zuzanna Natan Tomira Dagmara Orion Jan Cieszysława',
'05-25':'Magdalena Beda Leon Imisława Grzegorz Urban Leona',
'05-26':'Angelika Filip Adalwina Alwina Adalwin Alwin Emil Ewelina Paulina Więcemił Ariusz',
'05-27':'Lucjan Magdalena Oliwer Radowit Izydor Juliusz Jan',
'05-28':'Heladiusz Wilhelm Emil Priam Wiktor Ignacy German Augustyn Jaromir',
'05-29':'Maksymina Teodor Bogusława Maksymin Magdalena',
'05-30':'Feliks Ferdynand Joanna Andronik Sulimir',
'05-31':'Feliks Teodor Aniela Petronela Ernestyna Bożysława Petroniusz Petronia Ernesta',
'06-01':'Bernard Nikodem Alfons Gracjana Symeon Fortunat Magdalena Eunika Jakub Konrad',
'06-02':'Marzanna Marcelin Efrem Maria Trofima Erazm Racisław Nicefor Piotr Eugeniusz Mikołaj Marianna',
'06-03':'Tamara Konstantyn Owidiusz Leszek Paula Cecyliusz Ferdynand Klotylda Owidia',
'06-04':'Dacjusz Karol Braturad Bazyli Karp Franciszek Saturnina Gostmił Aleksander',
'06-05':'Walter Waleria Dobrociech Bonifacy Nikanor Dobromir Igor',
'06-06':'Norberta Dominika Benignus Symeon Więcerad Laurenty Klaudiusz Norbert Paulina',
'06-07':'Lukrecja Paweł Ada Robert Jarosław Antoni Hadriana Wisław Ciechomir Wiesław',
'06-08':'Wyszesław Wilhelm Medard Maksym Seweryn Adriana Karp',
'06-09':'Felicjan Pelagia Anna',
'06-10':'Bogumiła Mauryn Bogumił Apollo Małgorzata Edgar',
'06-11':'Feliks Teodozja Anastazy Radomił Barnaba',
'06-12':'Wyszemir Bazyli Onufry Władysława Jarogniewa Narcyz Antonina Leon Jan Jarogniew Leona Celestyna Władysław',
'06-13':'Herman Chociemir Lucjan Antoni Tobiasz',
'06-14':'Walerian Justyn Bazyli Eliza Ninogniew',
'06-15':'Bernard Abraham Nikifor Witold Witosław Wodzisław Jolanta Wit Leonida Lotar Angelina',
'06-16':'Benon Cyryk Ludgarda Aneta Budzimir Justyna Jan',
'06-17':'Izaura Wolmar Drogomysł Radomił Hipacy Franciszek Adrianna Laura Marcjan Rajner Adolf Waleriana',
'06-18':'Elżbieta Paula Marek Efrem Emil Gerwazy',
'06-19':'Michalina Borzysław Gerwazy Odo Protazy Julianna Eurydyka',
'06-20':'Bożena Bogna Rafał Gemma Florentyna Franciszek Hektor',
'06-21':'Teodor Domamir Demetria Alojza Alojzy Marcja Alban Rudolf Rudolfina Alicja Rudolfa',
'06-22':'Agenor Flawiusz Achacy Innocenta Broniwoj Paulina Achacjusz Innocenty Tomasz',
'06-23':'Józef Wanda Bazyli Piotr Agrypina Zenon Albin',
'06-24':'Emilia Wilhelm Danuta Jan',
'06-25':'Prosper Albrecht Wilhelm Eulogiusz Tolisława Febronia Febron',
'06-26':'Jeremiasz Paweł Zdziwoj Jan',
'06-27':'Włodzisław Cyryl Bożydar',
'06-28':'Paweł Olga Józef Zbrosław Leon Serena Leona Ireneusz',
'06-29':'Paweł Iweta Dalebor Piotr Benedykta',
'06-30':'Marcjalis Władysława Ciechosława Leon Emilia Leona Lucyna Trofim Władysław',
'07-01':'Bogusław Halina Estera Teobald Karolina Teodoryk Domicjan Domicjana Klarysa',
'07-02':'Otto Piotr Urban Martynian Bożydar Juda Niegosława Jagoda',
'07-03':'Jacek Miłosław Otto Otton Korneli Leon Anatol Leona',
'07-04':'Elżbieta Aurelian Aggeusz Alfred Teodor Józef Odon Odo Malwina Wielisław Innocenty Julian',
'07-05':'Zoe Marta Wilhelm Trofima Antoni Przybywoj Bartłomiej Jakub Filomena Karoliny',
'07-06':'Niegosław Dominika Nazaria Dominik Ignacja Gotard Agrypina Chociebor',
'07-07':'Benedykt Pompejusz Sędzisława Antoni Piotr Cyryl Wilibald Metody',
'07-08':'Adrian Kilian Kiliana Prokop Eugeniusz Wirginia Odeta Edgar Chwalimir',
'07-09':'Lukrecja Zenona Sylwia Anatola Adolfina Anatolia Weronika Ludwika Patrycjusz Róża Zenon Hieronim Mikołaj Lucja',
'07-10':'Filip Aniela Samson Zacheusz Witołd Amalberga Sylwan Witalis January Aleksander Rufina',
'07-11':'Benedykt Pius Pelagia Siepraw Olga Wyszesława Kallina Placyd Sawin Kalina Cyprian Cyrus',
'07-12':'Feliks Paweł Leon Epifania Gwalbert Leona Weronika Euzebiusz Piotr Tolimir Andrzej Henryk',
'07-13':'Radomiła Joel Ernest Eugeniusz Małgorzata Trofima Justyna Sara Jakub',
'07-14':'Marcelin Ulryk Marcelina Franciszek Dobrogost Kosma Ulryka Marceli Izabela Damian',
'07-15':'Lubomysł Daniel Włodzimierz Roksana Egon Ignacy Henryk Niecisław Dawid',
'07-16':'Dzierżysław Benedykt Faust Stefan Eustacjusz Eustachy Andrzej Marika Dzierżysław Carmen',
'07-17':'Januaria Donata Marcelina Dzierżykraj Konstancja Aneta Marceli Andrzej Aleksja Karolina Leon Aleksy Leona',
'07-18':'Robert Materna Erwin Uniesław Maternus Arnold Wespazjan Teodozja Szymon Kamil',
'07-19':'Alfred Arseniusz Wincenty Wodzisław Lutobor Rufin',
'07-20':'Paweł Eliasz Sewera Hieronim Małgorzata Leon Heliasz Czesław Leona',
'07-21':'Benedykt Prokop Daniel Ignacy Andrzej Wiktor Stojsław Paulina Prakseda',
'07-22':'Wawrzyniec Bolesława Więcemiła Magdalena Pankracy Laurencjusz Albin',
'07-23':'Bogna Apolinary Apolinaria',
'07-24':'Olga Krystiana Antoni Kinga Wojciecha Kunegunda Krystyna',
'07-25':'Walentyna Nieznamir Alfons Olimpia Rudolf Rudolfina Jakub Sławosław Krzysztof Rudolfa',
'07-26':'Anna Mirosława Grażyna Bartłomieja Hanna',
'07-27':'Aureli Pantaleon Antuza Natalia Bertold Laurenty Wszebor Lilia Julia Lilla',
'07-28':'Alfonsa Samson Pantaleon Marcela Wiktor Innocenty',
'07-29':'Konstantyn Olaf Maria Faustyn Serafina Marta Urban Beatrycze Lucyla Cierpisław',
'07-30':'Ubysław Ubysława Ludomiła Julita Maryna Abdon Julia Zdobysław',
'07-31':'Alfonsa Justyn Helena Demokryt Ignacy Ernesta Emilian Beat Ludomir',
'08-01':'Alfons Justyn Nadzieja Piotr Nadzieja Brodzisław Rudolf Rudolfina Konrad Rudolfa',
'08-02':'Gustaw Karina Maria Stefan Borzysława',
'08-03':'Nikodem Symeon Szczepan August Lidia',
'08-04':'Alfred Mironieg Dominik Maria Arystarch Protazy',
'08-05':'Stanisława Nonna Cyriak Maria Memiusz Oswalda Oswald',
'08-06':'Wincenty Felicysym Sława Stefan Jakub January',
'08-07':'Licyniusz Kajetan Klaudia Dobiemir Dorota Sykstus Andromeda Albert Doryda Licynia Konrad',
'08-08':'Niezamysł Cyriak Sylwiusz Cyryl Cyprian Emilian',
'08-09':'Klarysa Miłorad Domicjan Domicjana Roland Roman Jan Romuald',
'08-10':'Bernard Amadea Wawrzyniec Wierzchosław Asteria Hugona Bożydar Wirzchosław Filomena Prochor',
'08-11':'Lukrecja Herman Włodzimierz Tyburcja Zuzanna Ligia Aleksander',
'08-12':'Klara Lech Piotr Hilaria Leonida',
'08-13':'Radomiła Hipolit Diana Hipolita Kasjan Adriana Helena Wojbor Jan Gertruda',
'08-14':'Alfred Euzebiusz Atanazja Kalikst Dobrowoj Maksymilian Dobrowoja Machabeusz',
'08-15':'Napoleon Maria Stefan',
'08-16':'Ambroży Emil Roch Domarad Eleuteria Stefan',
'08-17':'Bertram Jacek Miron Zawisza Anita Jaczewoj Liberat Eliza Joanna Anastazja Julianna',
'08-18':'Klara Ilona Nela Tworzysława Helena Agapit Bogusława Bronisław',
'08-19':'Bolesław Ludwik Emilia Piotr Juliusz Jan Sebald Julian',
'08-20':'Bernard Samuel Sobiesław Sabin Sara Jan Samuela',
'08-21':'Bernard Franciszek Joanna Męcimir Adolf Filipina Emilian',
'08-22':'Fabrycjan Tymoteusz Fabrycy Dalegor Hipolit Namysław Maria Zygfryd Zygfryda Cezary',
'08-23':'Filip Róża Walerian Benicjusz Sulirad Zacheusz Laurenty Apolinary',
'08-24':'Michalina Halina Anita Cieszymir Bartłomiej Joanna Jerzy Malina Bartosz',
'08-25':'Sieciesław Kalasanty Ludwik Michał Elwira Grzegorz Luiza Gaudencjusz',
'08-26':'Sandra Wirzchosława Zefiryna Maria Maksym Dobroniega Joanna Wiktorian Konstanty Zefir Zefiryn',
'08-27':'Teodor Józef Gebhard Rufus Monika Amadea Małgorzata Przybymir Cezary',
'08-28':'Alfons Patrycja Joachima Stronisław Sobiesław Adelina Aleksy Augustyn Aleksander',
'08-29':'Mederyka Sabina Flora Racibor Mederyk Jan',
'08-30':'Gaudencja Miron Tekla Częstowoj Adaukt Rebeka',
'08-31':'Rajmund Bogdan Albertyna Ramona Paulina',
'09-01':'Idzi Bronisław Bronisława',
'09-02':'Absalon Dziesław Wilhelm Stefan Bogdan Eliza Tobiasz Dionizy Henryk Julian Czesław',
'09-03':'Manswet Eufemia Erazma Wincenty Antoni Bazylisa Szymona Mojmir Bartłomiej Zenon Szymon Joachim Izabela Natalis Jan Bronisław',
'09-04':'Rozalia Lilianna Rościgniew Daniela Hermiona Agatonik Ida',
'09-05':'Herakles Wawrzyniec Herkulan Dorota Stronisława Herkules Justyna',
'09-06':'Eugenia Michał Zachariasz Magnus Eugeniusz Zachary Albin Aleksja Uniewit Beata',
'09-07':'Sozont Melchior Ryszard Domasława Regina',
'09-08':'Radosława Maria Adrianna Radosław Nestor',
'09-09':'Gorgoniusz Aureliusz Otmar Edeltrauda Piotr Audomar Dionizy Ożanna',
'09-10':'Mścibor Klemens Leon Pulcheria Aldona Mikołaj Leona Łukasz Nimfodora',
'09-11':'Feliks Jacek Naczęsław Dagna Prot Jan',
'09-12':'Gwidon Maria Sylwin Piotr Radzimir Amadeusz  Cyrus Maja',
'09-13':'Eugenia Filip Aureliusz Morzysław Aleksander',
'09-14':'Bernard Materna Siemomysł Szymon Cyprian Maternus',
'09-15':'Nikodem Budzigniew Maria Albin Kaja',
'09-16':'Eugenia Edyta Jakub Kornel Eufemia Edda Sędzisław Antym Franciszek Kamila Sebastiana Wiktor Cyprian',
'09-17':'Ariadna Szczęsny Zygmunta Justyn Narcyz Hildegarda Lamberta Franciszek Szczęsna Dezyderiusz Drogosław Lambert Teodora Justyna',
'09-18':'Irena Józef Zachariasz Dobrowit Stefania Zachary Ryszarda Tytus Baltazar',
'09-19':'Więcemir Teodor Wilhelmina Marta Alfons Trofim Konstancja Festus January',
'09-20':'Klemens Mieczysława Irena Faustyna Oleg Eustachiusz Eustachy Filipina Fausta Dionizy',
'09-21':'Bernardyna Hipolit Jonasz Marek Laurenty Mateusz Ifigenia Bożeciech',
'09-22':'Daria Maurycy Tomasz Ignacy Joachim Prosimir',
'09-23':'Bogusław Liwiusz Tekla Boguchwała Libert',
'09-24':'Teodor Gerard Maria Uniegost Tomir',
'09-25':'Aureli Aurelia Aurelian Herkulan Wincenty Rufus Piotr Franciszek Gaspar Włodzisław Eufrozyna Kamil Władysław Kleofas',
'09-26':'Euzebiusz Justyna Cyprian',
'09-27':'Przedbor Kosma Urban Amadeusz  Damian',
'09-28':'Więcesław Wawrzyniec Salomon Wacława Marek Sylwin Wacław Laurencjusz Jan',
'09-29':'Michalina Michał Rafał Franciszek Dadźboga Dadźbog',
'09-30':'Wiara Felicja Grzegorz Zofia Hieronim Imisław Wiktor Honoriusz',
'10-01':'Remigiusz Cieszysław Benigna Igor Danuta Jan',
'10-02':'Leodegar Stanimir Teofil Dionizy',
'10-03':'Teresa Gerard Ewalda Gerarda Heliodor Ewald Kandyd Eustachy Józefa Sierosław',
'10-04':'Manfreda Rozalia Manfred Franciszek Konrad',
'10-05':'Justyn Faust Galla Petra Igor Placyd Konstancjusz Apolinary Flawiana',
'10-06':'Fryderyka Alberta Brunon Roman Bronisław',
'10-07':'Amalia Tekla Marek Maria Rościsława Stefan Justyna',
'10-08':'Laurencja Ewodia Demetriusz Pelagia Symeon Ewodiusz Marcjusz Brygida Artemon Wojsława',
'10-09':'Przedpełk Ludwik Arnold Dionizjusz Bogdan Atanazja Bożydar Sara Dionizy Jan',
'10-10':'Lutomir Kalistrat Przemysław Paulin Franciszek Tomiła German Tomił',
'10-11':'Burchard Germanik Maria Dobromiła Aldona Brunon Marian Emilian Placyda',
'10-12':'Witolda Wilfryd Serafin Cyriak Edwin Witold Salwin Grzymisław Eustachy Maksymiliana Maksymilian',
'10-13':'Daniel Geraldyna Wacław Wacława Maurycy Gerald Teofil Mikołaj Edward Siemisław',
'10-14':'Bernard Dominik Alan Dzierżymir Kalikst Fortunata',
'10-15':'Teresa Sewer Tekla Gościsława Brunon Jadwiga',
'10-16':'Aurelia Radzisław Ambroży Gerard Gaweł Emil Florentyna Grzegorz Dionizy Jadwiga',
'10-17':'Małgorzata Lucyna Laurentyna Augustyna Rudolf Wiktor Rudolfina Seweryna Sulisława Ignacy Marian Rudolfa',
'10-18':'Hanna Julian',
'10-19':'Paweł Pelagia Ziemowit Kleopatra Piotr Ferdynand Siemowit Skarbimir',
'10-20':'Budzisława Irena Wendelin Apollo Witalis',
'10-21':'Klementyna Elżbieta Hilary Bernard Dobromił Pelagia Celina Urszula Nunilona Wszebora',
'10-22':'Filip Sewer Kordula Marek Kordian Abercjusz Przybysława Alodia',
'10-23':'Teodor Seweryn Giedymin Odila Marlena Ignacy Roman Jan',
'10-24':'Filip Salomon Marcin Boleczest Marek Antoni Rafał',
'10-25':'Daria Chryzant Tarazjusz Bonifacy Teodozjusz Maur Sambor Inga Kryspin',
'10-26':'Ludomiła Ewaryst Lutosław Lucyna',
'10-27':'Frumencjusz Sabina Iwona Wincenty Siestrzemił',
'10-28':'Tadeusz Wszeciech Szymon Juda',
'10-29':'Teodor Narcyz Longin Lubgost Euzebia Franciszek Wioleta',
'10-30':'Zenobia Przemysław Klaudiusz Edmund',
'10-31':'Augusta Alfons Wolfgang Antoni August Urban Godzimir Antonina Lucyla Saturnin Narcyz',
'11-01':'Konradyn Seweryn Andrzej Warcisław Wiktoryna',
'11-02':'Wiktoryn Eudoksjusz Ambroży Stojmir Małgorzata Tobiasz Bogdana',
'11-03':'Sylwia Huberta Chwalisław Hubert Bogumił Cezary',
'11-04':'Karolina Dżesika Emeryk Karol Boromeusz Olgierd Modesta Witalis Mojżesz Emeryka Mściwoj Mszczujwoj',
'11-05':'Elżbieta Florian Zachariasz Trofima Marek Sławomir Zachary Blandyna Blandyn Dalemir',
'11-06':'Feliks Leonard Trzebowit Ziemowit Leonarda',
'11-07':'Achilles Karina Żelimir Amaranta Melchior Przemił Antoni Florentyn Engelbert',
'11-08':'Sędziwoj Sewerian Adrian Sewer Wiktoryn Godfryd Wiktoria Seweryn Klaudiusz Wiktor Hadrian',
'11-09':'Genowefa Teodor Bogodar Teodora Ursyn Nestor',
'11-10':'Probus Nimfa Stefan Andrzej Leon Leona Ludomir',
'11-11':'Jozafat Teodor Marcin Spycisław Bartłomiej Maciej Anastazja Prot',
'11-12':'Jozafat Konradyn Marcin Krystyn Witold Izaak Jonasz Renata Cibor Czcibor Konradyna Renat',
'11-13':'Brykcjusz Walentyn Eugeniusz Stanisław Liwia Augustyna Mikołaj Jan Arkadiusz',
'11-14':'Elżbieta Wszerad Józef Serapion Klementyn Judyta Hipacy Laurenty Kosma Agata Lewin Damian Agryppa',
'11-15':'Alfons Idalia Leopold Leopoldyna Roger Albert Przybygniew Artur',
'11-16':'Ariel Otmar Aureliusz Audomar Niedamir Piotr Dionizy Gertruda Edmund Patrokles',
'11-17':'Jozafat Hugo Karolina Palmira Zbysław Floryn Zacheusz Grzegorz Sulibor Dionizy',
'11-18':'Leonard Aniela Otto Otton Leonarda Galezy Odo Tomasz Cieszymysł Filipina Roman Gabriela',
'11-19':'Elżbieta Paweł Seweryn Mironiega Salomea',
'11-20':'Feliks Maksencja Ampeliusz Hieronim Sędzimir Edmund Anatol Oktawia Oktawiusz',
'11-21':'Janusz Twardosław Maria Elwira Albert Rufus Piotr Regina Konrad Wiesław',
'11-22':'Cecylia Marek Maur Wszemiła',
'11-23':'Klemens Adela Przedwoj Erast Orestes Felicyta Fotyna',
'11-24':'Dobrosław Gerarda Pęcisław Gerard Emilia Flora Ema Franciszek Protazy Jan Biruta',
'11-25':'Erazm Katarzyna Tęgomir',
'11-26':'Leonard Sylwester Dobiemiest Leonarda Delfin Lechosława Lechosław Jan Konrad',
'11-27':'Wirgiliusz Jozafat Zygfryd Stojgniew Gustaw Dominik Damazy Zygfryda Oda Walery Maksymilian',
'11-28':'Grzegorz Lesław Zdzisław Gościrad Lesława Jakub Rufin',
'11-29':'Klementyna Walter Błażej Bolemysł Przemysł Fryderyk Saturnin Paramon',
'11-30':'Zbysława Andrzej Justyna Konstancjusz Maura',

'12-01':'Iwa Eligia Natalia Platon Edmund Długosz Eligiusz Sobiesława',
'12-02':'Bibiana Aurelia Wiktoryn Zbylut Ludwina Blanka Balbina Sulisław Paulina Sylweriusz',
'12-03':'Uniemir Kasjan Lucjusz Franciszek Ksawery',
'12-04':'Klemens Chrystian Barbara Krystian Piotr Hieronim',
'12-05':'Anastazy Kryspina Sabina Gerald Pęcisława Krystyna',
'12-06':'Angelika Jarema Agata Dionizja Mikołaj Emilian Leoncja',
'12-07':'Ambroży Marcin Ninomysł Agaton',
'12-08':'Wirginiusz Maria Narcyza Apollo Boguwola',
'12-09':'Wielisława Leokadia Waleria Joachim Delfina Wiesław',
'12-10':'Nikoleta Daniel Judyta Maria Radzisława Andrzej Julia',
'12-11':'Stefan Damazy Waldemar Wojmir Julia',
'12-12':'Adelajda Dagmara Suliwuj Paramon Aleksander',
'12-13':'Bernarda Otylia Jodok Róża Włodzisława Auksencja Auksencjusz Auksenty',
'12-14':'Pompejusz Sławobor Alfred Nahum Arseniusz Noemi Spirydion Izydor',
'12-15':'Cecylia Walerian Celina Wolimir Fortunata',
'12-16':'Alina Adelajda Zdzisława Ananiasz Albina',
'12-17':'Florian Łazarz',
'12-18':'Bogusław Wszemir Arkadia Gracjan Wilibald Auksencja Auksencjusz Auksenty',
'12-19':'Tymoteusz Nemezjusz Abraham Dariusz Beniamin Urban Mścigniew',
'12-20':'Bogumiła Dominik Amon Liberat Dagmara Teofil',
'12-21':'Tomisław Balbin Tomasz Honorat Festus',
'12-22':'Ksaweryna Bożena Drogomir Ksawera Honorata Zenon Franciszka Gryzelda Flawian Beata',
'12-23':'Wiktoria Anatola Sławomir Sławomira Dagobert Anatolia',
'12-24':'Adela Grzymisława Druzjanna Ewa Godzisława Druzjanna Irmina Druzjan Adamina Grzegorz Ewelina Hermina Zenobiusz Tarsylia Tarsylla Adam',
'12-25':'Eugenia Spirydion Piotr Anastazja',
'12-26':'Wrociwoj Szczepan Dionizy',
'12-27':'Żaneta Fabia Radomysł Fabiola Jan Cezary',
'12-28':'Teofila Antoni Ema Dobrowieść Godzisław',
'12-29':'Trofim Jonatan Dominik Marcin Tomasz Gosław Dawid',
'12-30':'Dawida Sewer Anizja Irmina Eugeniusz Rajner Sabin Katarzyna Dionizy Uniedrog Dawid',
'12-31':'Korneliusz Sylwester Donata Mariusz Melania Saturnina Sebastian Tworzysław',

